import {validateConfig,base,read,write,coefficient as p,damage,control,job,apply,housekeeping,planning,committed,interrupted,SCALE} from './common.js';
const baseRequires=['status','schedule','legacy-effect'];
export function create(config){validateConfig(config);const {definition:a,hero,definitions}=config;
 const requires=[...baseRequires,'damage',...(a.id==='centaur_hoof_stomp'?['control','action-token']:[]),...(a.id==='centaur_double_edge'?['self-damage','target-route']:[])];
 return base(config,{requires,planCast:(ctx,e)=>planning(config,ctx,e),onCastCommitted:(ctx,e)=>committed(config,ctx,e),onInterrupt:(ctx,e)=>interrupted(config,ctx,e),
 activate(ctx,c){const s=read(ctx,definitions),f=ctx.actor(c.owner);if(a.mvp.passive)return;
  if(a.id==='centaur_hoof_stomp'){s.owners[c.owner].windup={until:ctx.now+p(a,'windup_time')};job(ctx,s,a,c,'stomp',p(a,'windup_time'),{},null,['control','input-cancel','action']);}
  else if(a.id==='centaur_double_edge'){const r=ctx.target.route({owner:c.owner,target:c.target,abilityId:a.id,range:a.mvp.range_wu,reflectable:true,reflected:c.reflected});if(!r.accepted)return;const t=ctx.actor(r.target);if(!t.alive||Math.abs(f.x-t.x)>a.mvp.range_wu+22)return;const amount=p(a,'edge_damage')+hero.attributes18.str*p(a,'strength_damage')/100;damage(ctx,a,r.owner,r.target,amount,'magical',{reflected:r.owner!==c.owner});ctx.selfDamage({actor:c.owner,abilityId:a.id,amount,nonlethal:true});}
  else if(a.id==='centaur_stampede')s.owners[c.owner].stampede={until:ctx.now+p(a,'duration'),hit:[]};write(ctx,s);
 },
 scheduledHandlers:a.id==='centaur_hoof_stomp'?{dispatch(ctx,d){if(ctx.actor(d.owner).heroId!==hero.registryNumericId)throw Error('Invalid Centaur scheduled owner');const s=read(ctx,definitions),own=s.owners[d.owner];own.jobs=own.jobs.filter(j=>j.handle!==d.jobHandle);if(d.op!=='stomp')throw Error('Unknown Centaur job');const f=ctx.actor(d.owner),t=ctx.actor(d.target);if(!f.alive||d.token!==null&&!ctx.action.valid(d.token)){write(ctx,s);return;}if(Math.abs(f.x-t.x)<=p(a,'radius')*SCALE+22&&t.y<45){damage(ctx,a,d.owner,d.target,p(a,'stomp_damage'),'magical');control(ctx,a,d.owner,d.target,'stun',p(a,'stun_duration'));}write(ctx,s);}}:{},
 onAttack(ctx,e){if(a.id!=='centaur_return'||!e.landed||e.attacker===e.target||e.target!==e.owner||!ctx.actor(e.owner).alive||!ctx.actor(e.owner).passivesEnabled)return;damage(ctx,a,e.owner,e.attacker,p(a,'return_damage')+hero.attributes18.str*p(a,'return_damage_str')/100,'physical',{reflected:true});},
 projectInterval(ctx,e){if(a.id!=='centaur_stampede'||e.kind!=='movement')return;const s=read(ctx,definitions).owners[e.owner],f=ctx.actor(e.owner);let speed=hero.move_speed;if(f.passivesEnabled)speed+=hero.attributes18.str*.4*SCALE;if(s.stampede)speed=Math.max(speed,330);return {multiplier:speed/hero.move_speed,disarmed:!!s.windup};},
 onStage(ctx,e){const s=read(ctx,definitions);housekeeping(ctx,s,e);if(a.id==='centaur_stampede'&&e.kind==='contact-check'){const own=s.owners[e.owner],stamp=own.stampede,f=ctx.actor(e.owner),t=ctx.actor(1-e.owner);if(stamp){if(f.alive&&t.alive&&!t.invulnerable&&!stamp.hit.includes(t.id)&&Math.abs(f.x-t.x)<=p(a,'radius')*SCALE+22){stamp.hit.push(t.id);damage(ctx,a,e.owner,t.id,hero.attributes18.str*p(a,'strength_damage'),'magical');apply(ctx,s,a,e.owner,t.id,'stampede_slow',p(a,'slow_duration'),{moveSlow:p(a,'slow_movement_speed')/100});}if(stamp.until<=ctx.now+1e-8)own.stampede=null;}}write(ctx,s);}
 });}
