import {JOB_OPS,validateConfig,base,read,write,coefficient as p,damage,control,apply,job,field,channel,cancelChannel,removeJobs,teleport,near,clamp,lookup,power,hasVeil,statusRows,effective,housekeeping,planning,committed,interrupted,SCALE} from './common.js';
const requires=['damage','heal','control','status','target-route','motion-request','protect','legacy-effect','schedule','action-token'];
export function create(config){validateConfig(config);const {definition:a,hero,definitions}=config,id=a.id;
 function dispatch(ctx,d){if(!JOB_OPS[id]?.includes(d.op)||ctx.actor(d.owner).heroId!==hero.registryNumericId||d.target!==1-d.owner||typeof d.castId!=='string'||!d.castId||d.op==='star'&&(!Number.isInteger(d.part)||d.part<0||d.part>2)||['sleight','remnant','gate','phase','hammer_out','hammer_return','solar_pulse','solar_land'].includes(d.op)&&(!Number.isFinite(d.x)||d.x<45||d.x>1155))throw Error('Invalid C scheduled delivery');const state=read(ctx,definitions),s=state.owners[d.owner],f=ctx.actor(d.owner),t=ctx.actor(d.target),cast={owner:d.owner,target:d.target,castId:d.castId};s.jobs=s.jobs.filter(j=>j.handle!==d.jobHandle);
  if(!f.alive||d.revision!==null&&d.revision!==s.revision||d.token!==null&&!(s.channel?.kind==='solar'&&s.channel.flight)&&!ctx.action.valid(d.token)){write(ctx,state);return;}
  const attack=()=>power(ctx,d.owner,definitions,d.attackBonus);
  switch(d.op){
   case 'sleight':if(t.alive&&Math.abs(t.x-d.x)<=p(a,'radius')*SCALE+22)damage(ctx,a,d.owner,d.target,attack()+p(a,'bonus_hero_damage'),'physical');break;
   case 'remnant':teleport(ctx,a,cast,d.owner,d.x);if(near(ctx.actor(d.owner),t,p(a,'radius')))damage(ctx,a,d.owner,d.target,p(a,'damage'),'magical');break;
   case 'gate':teleport(ctx,a,cast,d.owner,d.x);break;
   case 'phase':teleport(ctx,a,cast,d.owner,d.x);if(near(ctx.actor(d.owner),t,p(a,'damage_radius')))damage(ctx,a,d.owner,d.target,p(a,'AbilityDamage'),'magical');break;
   case 'star':if(near(f,t,p(a,'swipe_radius'))){damage(ctx,a,d.owner,d.target,attack()+p(a,'swipe_damage'),'physical');if(d.part===2)control(ctx,a,d.owner,d.target,'stun',p(a,'smash_stun_duration'));else apply(ctx,state,a,d.owner,d.target,'x_shortslow',.12,{moveSlow:1});}break;
   case 'hammer_out':case 'hammer_return':if(t.x>=Math.min(d.from,d.x)-110&&t.x<=Math.max(d.from,d.x)+110&&t.y<130)damage(ctx,a,d.owner,d.target,p(a,'hammer_damage'),'magical');if(d.op==='hammer_return')field(ctx,state,a,cast,'hammer_burn',d.x,4,d.from,{pulseInterval:.5,pulseLimit:8});break;
   case 'solar_pulse':ctx.heal({source:d.owner,target:d.owner,abilityId:a.id,amount:p(a,'base_heal')});if(Math.abs(t.x-d.x)<=p(a,'radius')*SCALE+22&&t.y<130)damage(ctx,a,d.owner,d.target,p(a,'base_damage'),'magical');break;
   case 'solar_fly':ctx.protect({actor:d.owner,abilityId:a.id,kind:'invulnerability',duration:p(a,'airtime_duration')});if(s.channel)s.channel.flight=true;break;
   case 'solar_land':teleport(ctx,a,cast,d.owner,d.x);if(near(ctx.actor(d.owner),t,p(a,'radius'))){damage(ctx,a,d.owner,d.target,p(a,'land_damage'),'magical');control(ctx,a,d.owner,d.target,'stun',p(a,'land_stun_duration'));}break;
   case 'deadshot':{const r=ctx.target.route({owner:d.owner,target:d.target,abilityId:a.id,range:1110,reflectable:true,reflected:false});if(r.accepted){const receipt=damage(ctx,a,r.owner,r.target,p(a,'damage'),'magical',{reflected:r.reflected,noReflect:r.noReflect});if(receipt.accepted)apply(ctx,state,a,r.owner,r.target,'x_deadslow',p(a,'impact_slow_duration'),{moveSlow:-p(a,'impact_slow_percent')/100},'negative',0,d.owner);}break;}
   case 'veil':apply(ctx,state,a,d.owner,d.owner,'x_veil',p(a,'duration'),{physicalImmune:true,veil:true},'positive');break;
   default:throw Error('Unknown C named job');
  }
  if(s.channel&&d.revision!==null&&['sleight','gate','phase','solar_land'].includes(d.op))s.channel=null;write(ctx,state);
 }
 function pulse(ctx,d){const prefix={ember_spirit_searing_chains:'x_chains',ember_spirit_flame_guard:'x_flame',abyssal_underlord_firestorm:'x_fireburn',void_spirit_astral_step:'x_voidmark'}[id];if(!prefix||ctx.actor(d.owner).heroId!==hero.registryNumericId||d.key!==prefix+'_'+d.owner||(id==='ember_spirit_flame_guard'?d.target!==d.owner:d.target!==1-d.owner))throw Error('Invalid C status pulse');const rows=statusRows(ctx,d.target,d.key);if(!rows.length||!ctx.actor(d.owner).alive||!ctx.actor(d.target).alive)return;const row=rows.find(r=>r.owner===d.owner);if(!row)return;
  if(id==='ember_spirit_searing_chains')damage(ctx,a,d.owner,d.target,p(a,'damage_per_second')*.25,'magical');
  else if(id==='abyssal_underlord_firestorm')damage(ctx,a,d.owner,d.target,ctx.actor(d.target).maxHp*p(a,'burn_damage')/100,'magical');
  else if(id==='void_spirit_astral_step')damage(ctx,a,d.owner,d.target,p(a,'pop_damage'),'magical');
  else if(id==='ember_spirit_flame_guard'&&row.values.amount>0&&near(ctx.actor(d.target),ctx.actor(1-d.target),p(a,'radius')))damage(ctx,a,d.target,1-d.target,p(a,'damage_per_second')*p(a,'tick_interval'),'magical');
 }
 function fieldStage(ctx,state,e){const own=state.owners[e.owner],f=own.effects.find(x=>x.handle===e.handle&&x.abilityId===a.id);if(!f)return;const view=ctx.legacyEffect.view(f.handle);if(!view?.alive){own.effects=own.effects.filter(x=>x.handle!==e.handle);return;}const source=ctx.actor(e.owner),t=ctx.actor(1-e.owner);if(!source.alive){ctx.legacyEffect.end(f.handle,'owner-dead');own.effects=own.effects.filter(x=>x.handle!==e.handle);return;}
  if(!Number.isFinite(e.ageSeconds)||e.ageSeconds<0||!Number.isInteger(e.pulses??0)||(e.pulses??0)<0||(e.pulses??0)>20)throw Error('Invalid bounded field fact');
  if(f.mode==='storm'){for(let i=0;i<e.pulses;i++)if(Math.abs(t.x-view.x)<=p(a,'radius')*SCALE+22&&t.y<130){damage(ctx,a,e.owner,t.id,p(a,'wave_damage'),'magical');apply(ctx,state,a,e.owner,t.id,'x_fireburn',p(a,'burn_duration'),{percent:p(a,'burn_damage')/100},'negative',p(a,'burn_interval'));}}
  else if(f.mode==='pit'){if(t.alive&&Math.abs(t.x-view.x)<=p(a,'radius')*SCALE+22&&t.y<130&&ctx.now>=(e.nextEligibleTime??0)){damage(ctx,a,e.owner,t.id,p(a,'pit_damage'),'magical');control(ctx,a,e.owner,t.id,'root',p(a,'ensnare_duration'),'basic');return {rearmAt:ctx.now+p(a,'pit_interval')};}}
  else if(f.mode==='aether'){const dx=(t.x-view.x)*f.face;if(e.ageSeconds>=p(a,'activation_delay')&&t.alive&&!t.invulnerable&&!t.debuffImmune&&dx>=-p(a,'remnant_watch_radius')*SCALE&&dx<=p(a,'remnant_watch_distance')*SCALE&&t.y<130){teleport(ctx,a,{castId:'effect:'+f.handle},t.id,view.x+f.face*p(a,'pull_destination')*SCALE);damage(ctx,a,e.owner,t.id,p(a,'impact_damage'),'magical');control(ctx,a,e.owner,t.id,'stun',p(a,'pull_duration'));ctx.legacyEffect.end(f.handle,'contact');own.effects=own.effects.filter(x=>x.handle!==f.handle);}}
  else if(f.mode==='hammer_burn'){for(let i=0;i<e.pulses;i++)if(t.x>=Math.min(f.from,view.x)-110&&t.x<=Math.max(f.from,view.x)+110&&t.y<130){damage(ctx,a,e.owner,t.id,p(a,'burn_damage')*.5,'magical');apply(ctx,state,a,e.owner,t.id,'x_hammer_slow',.6,{moveSlow:p(a,'move_slow')/100});}}
  else if(f.mode==='calling'){if(t.alive&&Math.abs(t.x-view.x)<=460*SCALE&&t.y<130){apply(ctx,state,a,e.owner,t.id,'x_call_slow',.2,{moveSlow:-p(a,'aura_movespeed_slow')/100});const touch=[0,1,2,3].some(i=>Math.abs(t.x-(view.x+p(a,'dead_zone_distance')*SCALE*Math.cos(e.ageSeconds*Math.PI/2+i*Math.PI/2)))<=p(a,'hit_radius')*SCALE);if(touch&&ctx.now>=(e.nextEligibleTime??0)){damage(ctx,a,e.owner,t.id,p(a,'damage'),'magical');apply(ctx,state,a,e.owner,t.id,'x_call_silence',p(a,'silence_duration'),{silence:true});return {rearmAt:ctx.now+1};}}}
 }
 return base(config,{requires,planCast:(ctx,e)=>planning(config,ctx,e),onCastCommitted:(ctx,e)=>committed(config,ctx,e),onInterrupt:(ctx,e)=>interrupted(config,ctx,e),scheduledHandlers:{...(JOB_OPS[id]?{dispatch}:{}),...(['ember_spirit_searing_chains','ember_spirit_flame_guard','abyssal_underlord_firestorm','void_spirit_astral_step'].includes(id)?{pulse}:{})},
 activate(ctx,c){if(a.mvp.passive)return;const state=read(ctx,definitions),s=state.owners[c.owner],f=ctx.actor(c.owner),t=ctx.actor(c.target),aim=c.aimX;
  switch(id){
   case 'ember_spirit_searing_chains':if(near(f,t,p(a,'radius'))){apply(ctx,state,a,c.owner,c.target,'x_chains',p(a,'duration'),{dps:p(a,'damage_per_second')},'negative',.25);control(ctx,a,c.owner,c.target,'root',p(a,'duration'),'basic');}break;
   case 'ember_spirit_sleight_of_fist':{const duration=p(a,'attack_interval'),rev=channel(ctx,state,c.owner,'sleight',duration);ctx.protect({actor:c.owner,abilityId:a.id,kind:'invulnerability',duration});job(ctx,state,a,c,'sleight',duration,{x:aim},rev,['control','input-cancel','movement','action']);break;}
   case 'ember_spirit_flame_guard':apply(ctx,state,a,c.owner,c.owner,'x_flame',p(a,'duration'),{amount:p(a,'absorb_amount'),dps:p(a,'damage_per_second')},'positive',p(a,'tick_interval'));break;
   case 'ember_spirit_fire_remnant':field(ctx,state,a,c,'remnant',aim,1);job(ctx,state,a,c,'remnant',1,{x:aim});break;
   case 'abyssal_underlord_firestorm':field(ctx,state,a,c,'storm',aim,6.000001,aim,{radius:p(a,'radius')*SCALE,pulseInterval:p(a,'wave_interval'),pulseLimit:p(a,'wave_count')});break;
   case 'abyssal_underlord_pit_of_malice':field(ctx,state,a,c,'pit',aim,p(a,'pit_duration'),aim,{radius:p(a,'radius')*SCALE,eachFrame:true,rearm:p(a,'pit_interval')});break;
   case 'abyssal_underlord_dark_portal':{const x=c.explicitAim?aim:(f.x<600?1155:45),rev=channel(ctx,state,c.owner,'gate',p(a,'warp_channel_duration'));field(ctx,state,a,c,'gate',f.x,p(a,'duration'),x);field(ctx,state,a,c,'gate',x,p(a,'duration'),f.x);job(ctx,state,a,c,'gate',p(a,'warp_channel_duration'),{x},rev,['control','input-cancel','movement','action']);break;}
   case 'void_spirit_aether_remnant':field(ctx,state,a,c,'aether',aim,p(a,'duration'),aim,{eachFrame:true,activationDelay:p(a,'activation_delay')});break;
   case 'void_spirit_dissimilate':{const duration=p(a,'phase_duration'),x=clamp(f.x+Math.sign(aim-f.x)*p(a,'first_ring_distance_offset')*SCALE),rev=channel(ctx,state,c.owner,'phase',duration);ctx.protect({actor:c.owner,abilityId:a.id,kind:'invulnerability',duration});job(ctx,state,a,c,'phase',duration,{x},rev,['control','input-cancel','movement','action']);break;}
   case 'void_spirit_resonant_pulse':{let amount=p(a,'base_absorb_amount');if(near(f,t,p(a,'radius'))&&damage(ctx,a,c.owner,c.target,p(a,'damage')).accepted)amount+=p(a,'absorb_per_hero_hit');apply(ctx,state,a,c.owner,c.owner,'x_pulse',p(a,'buff_duration'),{amount},'positive');break;}
   case 'void_spirit_astral_step':{const direction=Math.sign(aim-f.x)||f.dir,x=clamp(f.x+direction*Math.max(p(a,'min_travel_distance')*SCALE,Math.min(p(a,'max_travel_distance')*SCALE,Math.abs(aim-f.x))));teleport(ctx,a,c,c.owner,x);if(near(ctx.actor(c.owner),t,p(a,'radius'))){damage(ctx,a,c.owner,c.target,power(ctx,c.owner,definitions,c.attackBonus),'physical');apply(ctx,state,a,c.owner,c.target,'x_voidmark',p(a,'pop_damage_delay'),{moveSlow:p(a,'movement_slow_pct')/100,pop:p(a,'pop_damage')},'negative',p(a,'pop_damage_delay'));}break;}
   case 'dawnbreaker_fire_wreath':{const rev=channel(ctx,state,c.owner,'star',1.1);for(let part=0;part<3;part++)job(ctx,state,a,c,'star',(part+1)*1.1/3,{part},rev,['control','input-cancel','movement','action']);break;}
   case 'dawnbreaker_celestial_hammer':{const travel=Math.abs(aim-f.x)/(p(a,'projectile_speed')*SCALE);job(ctx,state,a,c,'hammer_out',travel,{from:f.x,x:aim});job(ctx,state,a,c,'hammer_return',travel*2+p(a,'pause_duration'),{from:f.x,x:aim});break;}
   case 'dawnbreaker_solar_guardian':{const x=c.explicitAim?aim:f.x,rev=channel(ctx,state,c.owner,'solar',p(a,'AbilityChannelTime')+p(a,'airtime_duration'));removeJobs(ctx,s,['hammer_out','hammer_return']);for(let i=1;i<=3;i++)job(ctx,state,a,c,'solar_pulse',i*p(a,'pulse_interval'),{x},rev,['control','input-cancel','movement','action']);job(ctx,state,a,c,'solar_fly',p(a,'AbilityChannelTime'),{x},rev,['control','input-cancel','movement','action']);job(ctx,state,a,c,'solar_land',p(a,'AbilityChannelTime')+p(a,'airtime_duration'),{x},rev,['control','input-cancel','movement','action']);break;}
   case 'muerta_the_calling':field(ctx,state,a,c,'calling',aim,p(a,'duration'),aim,{eachFrame:true});break;
   case 'muerta_dead_shot':job(ctx,state,a,c,'deadshot',Math.abs(t.x-f.x)/(p(a,'speed')*SCALE));break;
   case 'muerta_gunslinger':s.gunslinger=!s.gunslinger;break;
   case 'muerta_pierce_the_veil':job(ctx,state,a,c,'veil',p(a,'transform_duration'));break;
   default:throw Error('Unimplemented C V6 slot '+id);
  }write(ctx,state);
 },
 projectInterval(ctx,e){if(config.hero.abilities[0].id!==id||e.kind!=='movement')return;const s=read(ctx,definitions).owners[e.owner];return {multiplier:s.channel?0:1,disarmed:!!s.channel};},
 projectAttack(ctx,e){if(id==='abyssal_underlord_atrophy_aura'){let amount=e.amount;amount+=sumGain(ctx,e.attacker);const enemy=ctx.actor(1-e.attacker);if(enemy.heroId===106&&enemy.alive&&enemy.passivesEnabled&&near(ctx.actor(e.attacker),enemy,p(a,'radius')))amount=Math.max(0,amount-lookup(definitions).get(ctx.actor(e.attacker).heroId).attack*p(a,'damage_reduction_pct')/100);return {amount};}if(id==='muerta_pierce_the_veil'&&hasVeil(ctx,e.attacker))return {amount:e.amount+lookup(definitions).get(ctx.actor(e.attacker).heroId).attack*p(a,'base_damage_percent')/100,type:'magical'};},
 projectDamage(ctx,e){if(e.phase==='modify'){if(id==='muerta_pierce_the_veil'&&e.type==='physical'&&hasVeil(ctx,e.target))return {amount:0};if(id==='dawnbreaker_luminosity'&&e.attacker===e.owner&&e.basic&&!e.reflected&&ctx.actor(e.owner).passivesEnabled&&read(ctx,definitions).owners[e.owner].luminosity===3)return {amount:e.amount*p(a,'bonus_damage')/100};}
  if(e.phase==='before-shields'&&['ember_spirit_flame_guard','void_spirit_resonant_pulse'].includes(id)){const flame=id==='ember_spirit_flame_guard';if(e.type!==(flame?'magical':'physical'))return;const rows=[0,1].flatMap(i=>statusRows(ctx,e.target,(flame?'x_flame_':'x_pulse_')+i));let amount=e.amount;const statusDebits=[];for(const row of rows){const take=Math.min(row.values.amount,amount*(flame?p(a,'shield_pct_absorb')/100:1)),remainingAmount=row.values.amount-take;amount-=take;statusDebits.push({handle:row.handle,amountField:'amount',remainingAmount,removeWhenEmpty:true});}return {amount,statusDebits};}
 },
 onAttack(ctx,e){if(id==='dawnbreaker_luminosity'&&e.attacker===e.owner){const state=read(ctx,definitions),s=state.owners[e.owner];if(e.landed&&ctx.actor(e.owner).passivesEnabled){s.luminosity=(s.luminosity+1)%4;if(s.luminosity===0&&e.receipt?.attackId===e.attackId)ctx.heal({source:e.owner,target:e.owner,abilityId:a.id,amount:e.receipt.actual*p(a,'heal_pct')/100});}write(ctx,state);}if(id==='muerta_gunslinger'&&e.attacker===e.owner){const s=read(ctx,definitions).owners[e.owner],f=ctx.actor(e.owner),t=ctx.actor(e.target);if(f.alive&&s.gunslinger&&e.landed&&f.passivesEnabled&&t.alive&&ctx.random()<p(a,'double_shot_chance')/100){const veil=hasVeil(ctx,e.owner);damage(ctx,a,e.owner,e.target,power(ctx,e.owner,definitions,e.attackBonus)+(veil?hero.attack*p(lookup(definitions).get(ctx.actor(e.owner).heroId).abilities.find(x=>x.id==='muerta_pierce_the_veil'),'base_damage_percent')/100:0),veil?'magical':'physical');}}},
 onDeath(ctx,e){if(id!=='abyssal_underlord_atrophy_aura')return;const state=read(ctx,definitions),s=state.owners[e.owner],f=ctx.actor(e.owner),t=ctx.actor(e.actor);if(t.id!==f.id&&f.alive&&!s.deathSeen&&f.passivesEnabled&&near(f,t,p(a,'radius'))){apply(ctx,state,a,e.owner,e.owner,'x_atrophy_gain',p(a,'bonus_damage_duration'),{bonusDamage:p(a,'bonus_damage_from_hero')},'positive');s.deathSeen=true;}write(ctx,state);},
 onStage(ctx,e){const state=read(ctx,definitions);housekeeping(ctx,state,e);const result=e.kind==='field'?fieldStage(ctx,state,e):undefined;write(ctx,state);return result;}
 });
}
function sumGain(ctx,id){return [0,1].flatMap(i=>statusRows(ctx,id,'x_atrophy_gain_'+i)).reduce((n,r)=>n+(r.values.bonusDamage??0),0);}
