import {validateConfig,base,read,write,coefficient as p,damage,apply,field,statusRows,housekeeping,planning,committed,interrupted,SCALE} from './common.js';
const baseRequires=['status','schedule','legacy-effect'];
export function create(config){validateConfig(config);const {definition:a,hero,definitions}=config;
 const requires=[...baseRequires,...(a.id==='skywrath_mage_ancient_seal'?['target-route']:['damage']),...(['skywrath_mage_arcane_bolt','skywrath_mage_concussive_shot'].includes(a.id)?['projectile-request','target-route']:[])];
 return base(config,{requires,planCast:(ctx,e)=>planning(config,ctx,e),onCastCommitted:(ctx,e)=>committed(config,ctx,e),onInterrupt:(ctx,e)=>interrupted(config,ctx,e),
 activate(ctx,c){const s=read(ctx,definitions),f=ctx.actor(c.owner),t=ctx.actor(c.target);
  if(a.id==='skywrath_mage_arcane_bolt'||a.id==='skywrath_mage_concussive_shot'){if(!t.alive)return;const bolt=a.id==='skywrath_mage_arcane_bolt',amount=bolt?p(a,'bolt_damage')+hero.attributes18.int*p(a,'int_multiplier'):p(a,'damage');ctx.projectile({owner:c.owner,abilityId:a.id,castId:c.castId,direction:c.direction,speed:p(a,bolt?'bolt_speed':'speed')*SCALE,range:0,height:'both',contactHandler:'onContact',data:{profile:'c-v6-homing',target:c.target,origin:c.owner,damage:amount,lifetime:8,startYOffset:100,reflected:false,slow:bolt?null:{duration:p(a,'slow_duration'),amount:p(a,'movement_speed_pct')/100}}});}
  else if(a.id==='skywrath_mage_ancient_seal'){const r=ctx.target.route({owner:c.owner,target:c.target,abilityId:a.id,range:a.mvp.range_wu,reflectable:true,reflected:c.reflected});if(r.accepted)apply(ctx,s,a,r.owner,r.target,'seal',p(a,'seal_duration'),{magicAmp:-p(a,'resist_debuff')/100,silence:true},'negative',0,c.owner);}
  else if(a.id==='skywrath_mage_mystic_flare')field(ctx,s,a,c,'flare',Math.max(45,Math.min(1155,c.aimX)),p(a,'duration'),c.aimX,{radius:p(a,'radius')*SCALE,pulseInterval:p(a,'damage_interval'),pulseLimit:p(a,'duration')/p(a,'damage_interval'),heightLimit:100});write(ctx,s);
 },
 onContact(ctx,e){if(!['skywrath_mage_arcane_bolt','skywrath_mage_concussive_shot'].includes(a.id))return;const d=e.data,source=e.projectileOwner??e.owner;const bolt=a.id==='skywrath_mage_arcane_bolt',expectedDamage=bolt?p(a,'bolt_damage')+hero.attributes18.int*p(a,'int_multiplier'):p(a,'damage');if(!d||d.origin!==e.owner||d.damage!==expectedDamage||typeof d.reflected!=='boolean'||source!==(d.reflected?1-e.owner:e.owner)||d.target!==(d.reflected?e.owner:1-e.owner)||(!bolt&&(d.slow?.duration!==p(a,'slow_duration')||d.slow?.amount!==p(a,'movement_speed_pct')/100))||(bolt&&d.slow!==null))throw Error('Invalid C homing profile');if(d.profile!=='c-v6-homing'||!ctx.actor(source).alive||!ctx.actor(d.target).alive)return {end:true};const r=ctx.target.route({owner:source,target:d.target,abilityId:a.id,range:1110,reflectable:!d.reflected,reflected:d.reflected});if(!r.accepted)return {end:true};if(!d.reflected&&r.reflected)return {redirect:{owner:r.owner,target:r.target,reflected:true}};
  const s=read(ctx,definitions);damage(ctx,a,source,d.target,d.damage,'magical',{reflected:d.reflected});if(d.slow)apply(ctx,s,a,source,d.target,'concussive_slow',d.slow.duration,{moveSlow:d.slow.amount},'negative',0,d.origin);write(ctx,s);return {end:true};
 },
 projectDamage(ctx,e){if(a.id==='skywrath_mage_ancient_seal'&&e.phase==='modify'&&e.type==='magical'){const amp=statusRows(ctx,e.target,'seal').reduce((n,r)=>Math.max(n,r.values.magicAmp??0),0);return {amount:e.amount*(1+amp)};}
  if(a.id==='skywrath_mage_arcane_bolt'&&e.phase==='before-shields'&&e.target===e.owner&&e.type==='magical'){const s=read(ctx,definitions);let amount=e.amount;for(const b of s.owners[e.owner].barriers){const take=Math.min(b.amount,amount);b.amount-=take;amount-=take;}write(ctx,s);return {amount};}
 },
 onDamage(ctx,e){if(a.id!=='skywrath_mage_arcane_bolt'||e.attacker!==e.owner||e.actual<=0||e.attacker===e.target||e.reflected||e.type!=='magical'||!e.abilityIdOfDamage?.startsWith('skywrath_mage_')||!ctx.actor(e.owner).passivesEnabled)return;const s=read(ctx,definitions),list=s.owners[e.owner].barriers;if(list.length>=64)list.shift();list.push({amount:13.5,until:ctx.now+12});write(ctx,s);},
 onStage(ctx,e){const s=read(ctx,definitions);housekeeping(ctx,s,e);if(a.id==='skywrath_mage_mystic_flare'&&e.kind==='field'){const f=s.owners[e.owner].effects.find(x=>x.handle===e.handle&&x.abilityId===a.id),view=f&&ctx.legacyEffect.view(f.handle),t=ctx.actor(1-e.owner);if(view?.alive){const n=e.pulses;if(!Number.isInteger(n)||n<0||n>20)throw Error('Invalid Flare pulse fact');for(let i=0;i<n;i++)if(t.alive&&Math.abs(t.x-view.x)<=p(a,'radius')*SCALE+22&&t.y<100)damage(ctx,a,e.owner,t.id,p(a,'damage')/(p(a,'duration')/p(a,'damage_interval')),'magical');}else s.owners[e.owner].effects=s.owners[e.owner].effects.filter(x=>x.handle!==e.handle);}write(ctx,s);}
 });}
