import {base,validate,positive,percent,scale,EPS,actor,bounded,dt,obj,ownerShape,nullable,number,schema,damage,status,rows,enabledRows,missile,outputCue,planning} from './common.js';
import {withering,witheringHealing} from './innates.js';
const FILE='rules/core4/abaddon.js';
export function createAbaddon(c){const p=validate(c),id=c.definition.id;
 if(id==='abaddon_death_coil'){positive(p,['missile_speed']);percent(p,['self_damage','self_damage_enemy_target']);const cost=p.damage_heal*p.self_damage/100;if(cost>1e7)throw Error('Coil cost overflow');
  const finish=(ctx,e)=>{if(e.selfTarget){ctx.heal({source:e.owner,target:e.owner,abilityId:id,amount:p.damage_heal});return outputCue('core4-coil-self',c,e.owner);}return {projectile:missile(ctx,c,e,'core4-counter-missile',scale(p.missile_speed),c.definition.mvp.range_wu+22,{kind:'mist_coil',reflectionRange:c.definition.mvp.range_wu+22})};};
  return base(c,FILE,['heal','self-damage','status','projectile-request','damage'],{planCast:(ctx,e)=>planning(c,ctx,e,{targeted:e.selfTarget!==true}),activate(ctx,e){if(rows(ctx,e.owner,'borrowed_time').some(s=>s.remaining>0))ctx.heal({source:e.owner,target:e.owner,abilityId:id,amount:cost});else ctx.selfDamage({actor:e.owner,abilityId:id,amount:cost,nonlethal:true});return {automaticBorrowCheckpoint:{actor:e.owner,continuation:'coil-after-self-cost',cast:{owner:e.owner,target:e.target,castId:e.castId,selfTarget:e.selfTarget===true}},...outputCue('core4-coil-cost',c,e.owner,undefined,{nominal:cost,nonlethal:true})};},onStage(ctx,e){if(e.kind==='coil-after-self-cost')return finish(ctx,e.cast);},onContact(ctx,e){return damage(ctx,c,e.source,e.target,p.damage_heal,'magical',{dot:false,reflected:!!e.reflected,noLifesteal:!!e.reflected});}});
 }
 if(id==='abaddon_aphotic_shield'){positive(p,['duration']);const record=nullable(obj({amount:number(p.damage_absorb),life:number(p.duration)})),st=schema('aphotic-shield',obj({owners:ownerShape(record)})),read=ctx=>structuredClone(ctx.state.read()??{owners:{'0':null,'1':null}});
  const burst=(ctx,owner,reason)=>{const s=read(ctx),old=s.owners[owner];if(!old)return null;s.owners[owner]=null;ctx.state.write(s);const target=1-owner;if(ctx.actor(owner).alive&&ctx.target.distance(owner,target)<=scale(p.radius)+22)damage(ctx,c,owner,target,p.damage_absorb);return outputCue('core4-shield-end',c,owner,undefined,{reason,absorbed:p.damage_absorb-old.amount,radius:scale(p.radius)});};
  return base(c,FILE,['status','damage'],{planCast:(ctx,e)=>planning(c,ctx,e),activate(ctx,e){const replaced=burst(ctx,e.owner,'replaced');ctx.status.cleanse(e.owner,'strong',id);const s=read(ctx);s.owners[e.owner]={amount:p.damage_absorb,life:p.duration};ctx.state.write(s);return {replaced,...outputCue('core4-shield-start',c,e.owner,undefined,{amount:p.damage_absorb,life:p.duration})};},projectDamage(ctx,e){if(e.stage!=='shield')return;const s=read(ctx),i=actor(e.target),shield=s.owners[i];if(!shield||e.damage<=0)return {damage:e.damage};bounded(e.damage);const absorbed=Math.min(e.damage,shield.amount);shield.amount-=absorbed;ctx.state.write(s);const receipt={damage:e.damage-absorbed,absorbed,remaining:shield.amount,presentation:{kind:'core4-shield-absorb',actor:i,amount:absorbed,remaining:shield.amount}};if(shield.amount<=EPS)return {...receipt,burst:burst(ctx,i,'damage')};return receipt;},onStage(ctx,e){if(e.kind==='actor-live'){const s=read(ctx),i=actor(e.actor),shield=s.owners[i];if(!shield)return;shield.life-=dt(e);if(shield.life<=EPS)return burst(ctx,i,'expired');ctx.state.write(s);}if(e.kind==='shield-projection')return {shield:read(ctx).owners[actor(e.actor)]};},onDeath(ctx,e){const s=read(ctx);s.owners[actor(e.actor)]=null;ctx.state.write(s);}},st);
 }
 if(id==='abaddon_frostmourne'){positive(p,['curse_duration']);percent(p,['curse_slow']);return base(c,FILE,['status','damage'],{onDamage:(ctx,e)=>withering(c,ctx,e),projectHealing:witheringHealing,onAttack(ctx,e){if(ctx.actor(e.actor).heroId!==c.hero.registryNumericId||!e.landed||!ctx.actor(e.actor).passivesEnabled)return;return {handle:status(ctx,c,e.actor,e.target,'curse',p.curse_duration,{dps:p.curse_dps,moveSlow:p.curse_slow/100,attackBonus:p.curse_attack_speed,interval:.25},'basic')};},onStage(ctx,e){if(e.kind==='status-periodic'&&e.key==='curse')return damage(ctx,c,e.source,e.target,p.curse_dps*.25);if(e.kind==='movement-projection'){let slow=0;for(const s of enabledRows(ctx,e.actor,'curse'))slow=Math.max(slow,s.values.moveSlow);return {moveSlow:slow};}},projectInterval(ctx,e){const t=enabledRows(ctx,e.target,'curse').find(s=>s.owner===e.actor);return {attackSpeedBonus:t?p.curse_attack_speed:0};}});}
 if(id==='abaddon_borrowed_time'){positive(p,['duration']);const st=schema('borrowed-time',obj({remaining:ownerShape(number(p.duration))})),read=ctx=>structuredClone(ctx.state.read()??{remaining:{'0':0,'1':0}});
  const admit=(ctx,e)=>planning(c,ctx,{...e,activeRemaining:read(ctx).remaining[e.owner]},{borrowed:true});return base(c,FILE,['status','heal'],{planCast:admit,activate(ctx,e){const s=read(ctx),i=actor(e.owner);if(s.remaining[i]>0||!ctx.actor(i).alive||e.automatic&&!ctx.actor(i).passivesEnabled||!e.automatic&&ctx.actor(i).silenced)return {accepted:false};s.remaining[i]=p.duration;ctx.state.write(s);ctx.status.cleanse(i,'strong',id);status(ctx,c,i,i,'borrowed_time',p.duration,{convertIncomingDamage:true},'none',true,'positive');return {accepted:true,cancelCast:true,cancelSkillBuffer:true,preserveRecovery:true,...outputCue('core4-borrowed-time',c,i,undefined,{automatic:!!e.automatic,duration:p.duration})};},projectDamage(ctx,e){if(e.stage!=='borrowed')return;const i=actor(e.target),f=ctx.actor(i);if(!f.alive||read(ctx).remaining[i]<=0)return {damage:e.damage};bounded(e.damage);ctx.heal({source:i,target:i,abilityId:id,amount:e.damage});return {damage:0,converted:e.damage,healingSource:e.source};},onStage(ctx,e){if(e.kind==='actor-live'){const s=read(ctx),i=actor(e.actor);s.remaining[i]=Math.max(0,s.remaining[i]-dt(e));ctx.state.write(s);return {borrowedRemaining:s.remaining[i]};}if(e.kind==='automatic-borrow-check'){const i=actor(e.actor),f=ctx.actor(i),s=read(ctx);if(f.heroId===c.hero.registryNumericId&&f.alive&&f.hp<p.hp_threshold&&f.passivesEnabled&&s.remaining[i]<=0&&bounded(e.cooldownRemaining,0,3600)<=EPS)return {automaticCastRequested:true,actor:i,slot:3,cost:0};return {automaticCastRequested:false};}if(e.kind==='borrowed-projection')return {remaining:read(ctx).remaining[actor(e.actor)]};},onDeath(ctx,e){const s=read(ctx);s.remaining[actor(e.actor)]=0;ctx.state.write(s);}},st);
 }
 throw Error('Unknown Abaddon selected slot');
}
