import {codeIdentity} from '../../contract/code-identity.js';
import {damage,status,enabledRows,scale,actor,bounded} from './common.js';
// Fixed adaptations from the frozen private Core4 source. They are not added
// roster slots. The finite legacy effect alias is proposed for private validation.
export const INNATES=Object.freeze({seaborn:Object.freeze({armor:5.4,attackMultiplier:1.222,moveMultiplier:1.18,regenAmount:3.125,regenInterval:.5}),predator:Object.freeze({missingHpDamage:100,factor:.25}),withering:Object.freeze({duration:5,hpThresholdFraction:.4,healingMultiplier:.665,reduction:.335})});
export function seaborn(config,bash){const p=INNATES.seaborn;return {...bash,...codeIdentity(['rules/core4/bash.js','rules/core4/common.js','rules/core4/innates.js','rules/core4/index.js']),requires:[...bash.requires,'heal'],projectAttack(ctx,e){return {damage:e.water&&ctx.actor(e.actor).heroId===config.hero.registryNumericId&&ctx.actor(e.actor).passivesEnabled?e.damage*p.attackMultiplier:e.damage};},projectDamage(ctx,e){if(e.stage==='armor'&&e.type==='physical')return {armorAdd:e.water&&ctx.actor(e.target).heroId===config.hero.registryNumericId&&ctx.actor(e.target).passivesEnabled?p.armor:0};},onStage(ctx,e){if(e.kind==='movement-projection')return {speedMultiplier:e.water&&ctx.actor(e.actor).heroId===config.hero.registryNumericId&&ctx.actor(e.actor).passivesEnabled?p.moveMultiplier:1};if(e.kind==='water-regeneration'){if(e.water&&ctx.actor(e.actor).heroId===config.hero.registryNumericId&&ctx.actor(e.actor).alive&&ctx.actor(e.actor).passivesEnabled)return ctx.heal({source:e.actor,target:e.actor,abilityId:config.definition.id,amount:p.regenAmount});}if(e.kind==='water-regeneration-profile')return {enabled:e.water&&ctx.actor(e.actor).heroId===config.hero.registryNumericId&&ctx.actor(e.actor).passivesEnabled,interval:p.regenInterval,resetWhenDisabled:true};}};}
export function predator(ctx,e){const target=ctx.actor(e.target);if(ctx.actor(e.actor).heroId!==45||!e.landed||!target.alive||!ctx.actor(e.actor).passivesEnabled)return;bounded(target.maxHp,.001,1e7);bounded(target.hp,0,target.maxHp);return {innateDamage:{effectAlias:'viper_predator',source:actor(e.actor),target:actor(e.target),amount:(1-target.hp/target.maxHp)*INNATES.predator.missingHpDamage*INNATES.predator.factor,type:'physical',blockable:false,dot:true,passive:true}};}
export function withering(config,ctx,e){if(ctx.actor(e.source).heroId!==config.hero.registryNumericId||e.damage<=0||e.source===e.target||!ctx.actor(e.source).alive||!ctx.actor(e.source).passivesEnabled)return;return status(ctx,config,e.source,e.target,'withering',INNATES.withering.duration,{healReduction:INNATES.withering.reduction},'none');}
export function witheringHealing(ctx,e){const f=ctx.actor(e.actor);return {amount:enabledRows(ctx,e.actor,'withering').length&&f.hp/f.maxHp<INNATES.withering.hpThresholdFraction?e.amount*INNATES.withering.healingMultiplier:e.amount};}
