import {base,validate,positive,percent,scale,EPS,actor,bounded,dt,obj,ownerShape,number,schema,damage,status,enabledRows,field,outputCue,planning} from './common.js';
const FILE='rules/core4/razor.js';
export function createRazor(c){const p=validate(c),id=c.definition.id;
 if(id==='razor_plasma_field'){positive(p,['total_ability_time','radius']);percent(p,['slow_min','slow_max']);if(p.damage_max<p.damage_min||p.slow_max<p.slow_min)throw Error('Reversed Plasma coefficients');return base(c,FILE,['legacy-effect','damage','status'],{
  planCast:(ctx,e)=>planning(c,ctx,e),activate(ctx,e){return {effect:field(ctx,c,e,'core4-returning-ring',scale(p.radius),p.total_ability_time,{halfTime:p.total_ability_time/2,contactHandler:'onContact',contactPadding:22,oneHitPerPhase:true})};},
  onContact(ctx,e){if(!['out','back'].includes(e.phase))throw Error('Invalid Plasma phase');const fraction=Math.max(0,Math.min(1,bounded(e.distance)/scale(p.radius)));damage(ctx,c,e.source,e.target,p.damage_min+(p.damage_max-p.damage_min)*fraction);status(ctx,c,e.source,e.target,'plasma_slow',p.slow_duration,{moveSlow:(p.slow_min+(p.slow_max-p.slow_min)*fraction)/100},'basic');return outputCue('core4-plasma-contact',c,e.source,e.target,{phase:e.phase,distance:e.distance});},
  onStage(ctx,e){if(e.kind==='movement-projection'){let slow=0;for(const s of enabledRows(ctx,e.actor,'plasma_slow'))slow=Math.max(slow,s.values.moveSlow);return {moveSlow:slow};}}
 });}
 if(id==='razor_static_link'){positive(p,['drain_length','drain_duration']);const link=obj({handle:{type:'string',minLength:1,maxLength:160},owner:{type:'integer',minimum:0,maximum:1},target:{type:'integer',minimum:0,maximum:1},amount:number(Math.min(1e7,p.drain_rate*p.drain_length)),age:number(p.drain_length),draining:{type:'boolean'}}),st=schema('static-link',obj({links:{type:'array',maxItems:32,items:link}}));if(p.drain_rate*p.drain_length>1e7)throw Error('Link bound overflow');
  const read=ctx=>structuredClone(ctx.state.read()??{links:[]});return base(c,FILE,['legacy-effect'],{
   planCast:(ctx,e)=>planning(c,ctx,e,{targeted:true}),activate(ctx,e){if(!ctx.actor(e.target).alive||ctx.target.distance(e.owner,e.target)>c.definition.mvp.range_wu+22)return;const s=read(ctx);if(s.links.length>=32)throw Error('Core4 link capacity');const h=field(ctx,c,e,'core4-static-link',c.definition.mvp.range_wu,p.drain_length+p.drain_duration,{target:e.target,leash:c.definition.mvp.range_wu+scale(p.drain_range_buffer),callback:'onStage'});s.links.push({handle:h,owner:e.owner,target:e.target,amount:0,age:0,draining:true});ctx.state.write(s);return {handle:h};},
   onStage(ctx,e){if(e.kind==='link-step'){const s=read(ctx),l=s.links.find(x=>x.handle===e.handle);if(!l)return;let ended=false;const wasDraining=l.draining;if(l.draining){if(!ctx.actor(l.owner).alive||!ctx.actor(l.target).alive||ctx.target.distance(l.owner,l.target)>c.definition.mvp.range_wu+scale(p.drain_range_buffer)){l.draining=false;ended=true;}else{const live=Math.min(dt(e),p.drain_length-l.age);l.age+=live;l.amount+=p.drain_rate*live;if(l.age>=p.drain_length-EPS)l.draining=false;}}ctx.state.write(s);return {amount:l.amount,draining:l.draining,...(wasDraining&&!l.draining?{retainedSeconds:p.drain_duration}:{}),...(ended?outputCue('core4-link-break',c,l.owner,l.target,{amount:l.amount}):{})};}if(e.kind==='link-end'){const s=read(ctx);s.links=s.links.filter(l=>l.handle!==e.handle);ctx.state.write(s);}if(e.kind==='moving-attack'){return {allowed:read(ctx).links.some(l=>l.owner===e.actor&&l.draining)};}},
   projectAttack(ctx,e){let value=e.damage;for(const l of read(ctx).links){if(l.owner===e.actor)value+=l.amount;if(l.target===e.actor)value-=l.amount;}return {damage:value};},
   onDeath(ctx,e){const s=read(ctx),changed=s.links.filter(l=>l.owner===e.actor||l.target===e.actor);for(const l of changed)l.draining=false;ctx.state.write(s);return {retainLinks:changed.map(l=>({handle:l.handle,maxRemaining:p.drain_duration}))};}
  },st);
 }
 if(id==='razor_storm_surge'){positive(p,['strike_internal_cd']);percent(p,['strike_pct_chance','strike_move_slow_pct']);const st=schema('storm-surge',obj({cooldowns:ownerShape(number(p.strike_internal_cd))})),read=ctx=>structuredClone(ctx.state.read()??{cooldowns:{'0':0,'1':0}});
  const proc=(ctx,e,targeted)=>{const source=actor(e.actor),target=actor(e.target),f=ctx.actor(source),t=ctx.actor(target),s=read(ctx);if(f.heroId!==c.hero.registryNumericId||!f.alive||!t.alive||!f.passivesEnabled||s.cooldowns[source]>0||ctx.target.distance(source,target)>scale(p.strike_search_radius)+22||!targeted&&ctx.random()>=p.strike_pct_chance/100)return;s.cooldowns[source]=p.strike_internal_cd;ctx.state.write(s);damage(ctx,c,source,target,p.strike_damage,'magical',{reflected:true,noReflect:true,noLifesteal:true,passive:true});status(ctx,c,source,target,'storm_surge',p.strike_slow_duration,{moveSlow:p.strike_move_slow_pct/100});return outputCue('core4-storm-surge',c,source,target,{targeted});};
  return base(c,FILE,['damage','status'],{onTargeted:(ctx,e)=>proc(ctx,e,true),onDamage(ctx,e){if(e.damage<=0||e.source===e.target||e.reflected||e.noReflect||!e.basic)return;return proc(ctx,{actor:e.target,target:e.source},false);},onStage(ctx,e){if(e.kind==='actor-live'){const s=read(ctx);s.cooldowns[actor(e.actor)]=Math.max(0,s.cooldowns[e.actor]-dt(e));ctx.state.write(s);}if(e.kind==='movement-projection'){let slow=0;for(const s of enabledRows(ctx,e.actor,'storm_surge'))slow=Math.max(slow,s.values.moveSlow);return {moveSlow:slow};}}},st);
 }
 if(id==='razor_eye_of_the_storm'){positive(p,['duration','strike_interval']);return base(c,FILE,['legacy-effect','damage','status'],{planCast:(ctx,e)=>planning(c,ctx,e),activate(ctx,e){return {effect:field(ctx,c,e,'core4-eye-storm',scale(p.radius),p.duration,{interval:p.strike_interval,firstTick:p.strike_interval,followOwner:true,callback:'onStage',priority:'ward-unless-live-linked-hero'})};},onStage(ctx,e){if(e.kind==='storm-strike'){if(!ctx.actor(e.source).alive)return {end:true};if(e.wardChosen)return {endWard:{handle:e.wardHandle,reason:'attack'},...outputCue('core4-storm-ward',c,e.source,undefined,{wardX:bounded(e.wardX,0,1200)})};const t=ctx.actor(e.target);if(!t.alive||t.invulnerable||ctx.target.distance(e.source,e.target)>scale(p.radius)+22)return;damage(ctx,c,e.source,e.target,p.damage,'physical');const key='storm_armor_'+e.handle,old=enabledRows(ctx,e.target,key)[0];if(old)return {statusArmorDelta:{handle:old.handle,delta:-p.armor_reduction,preserveTick:true},...outputCue('core4-storm-strike',c,e.source,e.target,{stormHandle:e.handle})};status(ctx,c,e.source,e.target,key,Math.max(dt(e),bounded(e.remaining,0,p.duration)),{armor:-p.armor_reduction},'none',true);return outputCue('core4-storm-strike',c,e.source,e.target,{stormHandle:e.handle});}if(e.kind==='storm-owner-death')return {removeArmorKey:'storm_armor_'+e.handle};},projectDamage(ctx,e){if(e.type!=='physical'||e.stage!=='armor')return;let armor=0;for(const row of e.ownedStormStatuses??[]){if(row.effective)armor+=bounded(row.armor,-1e7,1e7);}return {armorAdd:armor};}});
 }
 throw Error('Unknown Razor selected slot');
}
