import {base,validate,positive,percent,scale,EPS,actor,bounded,dt,obj,ownerShape,nullable,number,schema,damage,status,enabledRows,field,outputCue,planning} from './common.js';
const FILE='rules/core4/slardar.js';
export function createSlardar(c){const p=validate(c),id=c.definition.id;
 if(id==='slardar_sprint'){positive(p,['duration','speed_burst_max_duration']);percent(p,['bonus_speed','slow_resistance_tooltip']);if(p.duration<=p.speed_burst_max_duration)throw Error('Invalid sprint tail');return base(c,FILE,['status'],{planCast:(ctx,e)=>({...planning(c,ctx,e),recoverySeconds:0}),activate(ctx,e){status(ctx,c,e.owner,e.owner,'sprint',p.duration,{profile:'core4-sprint',speedBonus:p.bonus_speed/100,burstDuration:p.speed_burst_max_duration,resistance:p.slow_resistance_tooltip/100},'none',true,'positive');return {recoverySeconds:0};},onStage(ctx,e){if(e.kind!=='movement-projection')return;const s=enabledRows(ctx,e.actor,'sprint')[0];if(!s)return {speedMultiplier:1,slowResistance:0};const age=bounded(s.elapsed,0,p.duration),remaining=bounded(s.remaining,0,p.duration),resist=age<=p.speed_burst_max_duration?p.slow_resistance_tooltip/100:Math.max(0,remaining/(p.duration-p.speed_burst_max_duration))*p.slow_resistance_tooltip/100;return {speedMultiplier:1+p.bonus_speed/100,slowResistance:resist};}});}
 if(id==='slardar_slithereen_crush'){positive(p,['puddle_duration']);return base(c,FILE,['legacy-effect','damage','control','status'],{planCast:(ctx,e)=>planning(c,ctx,e),activate(ctx,e){const radius=scale(p.crush_radius),h=field(ctx,c,e,'core4-water',scale(p.puddle_radius),p.puddle_duration,{groundOnly:true});const t=ctx.actor(e.target);if(ctx.target.distance(e.owner,e.target)<=radius+22&&t.y<45){damage(ctx,c,e.owner,e.target,p.crush_damage,'physical',{dot:false});ctx.control.apply({owner:e.owner,target:e.target,abilityId:id,key:'crush',type:'stun',duration:p.stun_duration,pierces:false,dispel:'strong'});status(ctx,c,e.owner,e.target,'crush',p.crush_extra_slow_duration+p.stun_duration,{moveSlow:-p.crush_extra_slow/100,attackSlow:-p.crush_attack_slow_tooltip,delay:p.stun_duration},'strong');}return {effect:h,...outputCue('core4-crush',c,e.owner,undefined,{radius})};},projectInterval(ctx,e){let attackSlow=0;for(const s of enabledRows(ctx,e.actor,'crush'))if(s.elapsed>=p.stun_duration)attackSlow=Math.max(attackSlow,-p.crush_attack_slow_tooltip);return {attackSlowMax:attackSlow};},onStage(ctx,e){if(e.kind==='movement-projection'){let moveSlow=0;for(const s of enabledRows(ctx,e.actor,'crush'))if(s.elapsed>=p.stun_duration)moveSlow=Math.max(moveSlow,-p.crush_extra_slow/100);return {moveSlow};}}});}
 if(id==='slardar_amplify_damage'){positive(p,['duration','puddle_duration']);const trail=nullable(obj({handle:{type:'string',minLength:1,maxLength:160},owner:{type:'integer',minimum:0,maximum:1},tick:number(.15),lastX:number(1200,0)})),st=schema('haze-trails',obj({targets:ownerShape(trail)})),read=ctx=>structuredClone(ctx.state.read()??{targets:{'0':null,'1':null}});
  return base(c,FILE,['status','legacy-effect'],{planCast:(ctx,e)=>planning(c,ctx,e,{targeted:true}),activate(ctx,e){const h=status(ctx,c,e.owner,e.target,'haze',p.duration,{armor:p.armor_reduction,revealed:true},'basic',true);if(h){const s=read(ctx);s.targets[e.target]={handle:h,owner:e.owner,tick:0,lastX:ctx.actor(e.target).x};ctx.state.write(s);}return outputCue('core4-haze',c,e.owner,e.target);},projectDamage(ctx,e){if(e.stage!=='armor'||e.type!=='physical')return;return {armorAdd:enabledRows(ctx,e.target,'haze').reduce((sum,s)=>sum+s.values.armor,0)};},onStage(ctx,e){if(e.kind==='haze-live'){const s=read(ctx),target=actor(e.target),trail=s.targets[target];if(!trail||trail.handle!==e.handle)return;trail.tick-=dt(e);if(trail.tick<=0){trail.tick=.15;const x=ctx.actor(target).x;if(Math.abs(x-trail.lastX)>=20||e.waterNearby===false){trail.lastX=x;ctx.state.write(s);const h=ctx.legacyEffect.spawn({owner:trail.owner,abilityId:id,castId:e.castId,kind:'area',x,radius:scale(p.puddle_radius),duration:p.puddle_duration,data:{profile:'core4-water',groundOnly:true}});return {effect:h};}}ctx.state.write(s);}if(e.kind==='haze-removed'){const s=read(ctx);if(s.targets[e.target]?.handle===e.handle){s.targets[e.target]=null;ctx.state.write(s);}}if(e.kind==='reveal-projection')return {revealed:enabledRows(ctx,e.actor,'haze').length>0};},onDeath(ctx,e){const s=read(ctx);s.targets[actor(e.actor)]=null;ctx.state.write(s);}},st);
 }
 throw Error('Unknown Slardar selected slot');
}
