import {base,validate,positive,percent,scale,EPS,actor,bounded,dt,obj,ownerShape,number,schema,damage,status,rows,enabledRows,missile,outputCue,planning} from './common.js';
import {predator} from './innates.js';
const FILE='rules/core4/viper.js';
export function createViper(c){const p=validate(c),id=c.definition.id;
 if(id==='viper_poison_attack'){positive(p,['duration']);percent(p,['movement_speed','magic_resistance']);if(!Number.isSafeInteger(p.max_stacks)||p.max_stacks<1||p.max_stacks>64)throw Error('Invalid poison stacks');const st=schema('poison-toggle',obj({enabled:ownerShape({type:'boolean'})})),read=ctx=>structuredClone(ctx.state.read()??{enabled:{'0':false,'1':false}});
  return base(c,FILE,['mana','status','damage'],{planCast:(ctx,e)=>planning(c,ctx,e,{toggle:true}),activate(ctx,e){const s=read(ctx),i=actor(e.owner);s.enabled[i]=!s.enabled[i];ctx.state.write(s);return {toggle:s.enabled[i],cost:0,presentation:{kind:'core4-poison-toggle',actor:i,enabled:s.enabled[i]}};},projectAttack(ctx,e){const f=ctx.actor(e.actor);if(f.heroId!==c.hero.registryNumericId||!read(ctx).enabled[e.actor]||f.mp<p.AbilityManaCost)return {damage:e.damage,corePoison:false};ctx.mana({actor:e.actor,abilityId:id,delta:-p.AbilityManaCost});return {damage:e.damage,corePoison:true,attackCost:p.AbilityManaCost};},onAttack(ctx,e){if(ctx.actor(e.actor).heroId!==c.hero.registryNumericId||!e.landed||!e.corePoison||!ctx.actor(e.target).alive||ctx.actor(e.target).debuffImmune)return;const h=status(ctx,c,e.actor,e.target,'poison',p.duration,{profile:'core4-poison-stack',stackLimit:p.max_stacks,replacement:'lowest-life',dps:p.damage,moveSlow:p.movement_speed/100,magicAmplification:p.magic_resistance/100,interval:.25},'basic');return {handle:h,...outputCue('core4-poison-stack',c,e.actor,e.target)};},onStage(ctx,e){if(e.kind==='status-periodic'&&e.key==='poison'){return damage(ctx,c,e.source,e.target,p.damage*.25);}if(e.kind==='movement-projection'){const n=ctx.actor(e.actor).debuffImmune?0:rows(ctx,e.actor,'poison').filter(s=>s.remaining>EPS).length;return {moveSlow:n*p.movement_speed/100};}},projectDamage(ctx,e){if(e.type!=='magical'||e.stage!=='core-magical')return;const n=ctx.actor(e.target).debuffImmune?0:rows(ctx,e.target,'poison').filter(s=>s.remaining>EPS).length;return {damage:e.damage*(1+n*p.magic_resistance/100)};},onDeath(ctx,e){const s=read(ctx);s.enabled[actor(e.actor)]=false;ctx.state.write(s);}},st);
 }
 if(id==='viper_nethertoxin'){positive(p,['max_duration','duration','projectile_speed']);if(p.max_damage<p.min_damage||p.max_damage*60>1e7)throw Error('Invalid toxin damage bound');const target=obj({exposure:number(3600),owner:{anyOf:[{type:'null'},{type:'integer',minimum:0,maximum:1}]}}),st=schema('toxin-exposure',obj({targets:ownerShape(target)})),read=ctx=>structuredClone(ctx.state.read()??{targets:{'0':{exposure:0,owner:null},'1':{exposure:0,owner:null}}});
  return base(c,FILE,['projectile-request','legacy-effect','damage'],{planCast:(ctx,e)=>planning(c,ctx,e),activate(ctx,e){const f=ctx.actor(e.owner),aim=Math.max(45,Math.min(1155,Math.max(f.x-c.definition.mvp.range_wu,Math.min(f.x+c.definition.mvp.range_wu,bounded(e.aimX,0,1200)))));return {projectile:missile(ctx,c,e,'core4-toxin-point',scale(p.projectile_speed),1200,{targetX:aim,originOffsetY:85,reflectable:false})};},onContact(ctx,e){return {effect:ctx.legacyEffect.spawn({owner:e.source,abilityId:id,castId:e.castId,kind:'area',x:bounded(e.x,45,1155),radius:scale(p.radius),duration:p.duration,data:{profile:'core4-toxin',groundHeight:45,contactPadding:22,callback:'onStage'}})};},onStage(ctx,e){if(e.kind!=='toxin-step')return;const target=actor(e.target),f=ctx.actor(target),s=read(ctx),v=s.targets[target];if(e.inside&&f.alive&&!f.invulnerable&&!f.debuffImmune){const before=v.exposure;v.exposure+=dt(e);v.owner=actor(e.source);if(v.exposure>3600)throw Error('Core4 toxin exposure overflow');const avg=(Math.min(p.max_duration,before)+Math.min(p.max_duration,v.exposure))/2;ctx.state.write(s);const receipt=damage(ctx,c,v.owner,target,(p.min_damage+(p.max_damage-p.min_damage)*avg/p.max_duration)*dt(e));return {exposure:v.exposure,toxinOwner:v.owner,receipt};}v.exposure=0;v.owner=null;ctx.state.write(s);return {exposure:0,toxinOwner:null};},projectInterval(ctx,e){return {attackSlowMax:read(ctx).targets[e.actor].exposure>0&&!ctx.actor(e.actor).debuffImmune?p.attack_slow:0};}},st);
 }
 if(id==='viper_corrosive_skin'){positive(p,['duration']);percent(p,['bonus_magic_resistance']);return base(c,FILE,['status','damage'],{onAttack:predator,projectDamage(ctx,e){if(e.stage==='core-magical'&&e.type==='magical')return {damage:e.damage*(ctx.actor(e.target).heroId===c.hero.registryNumericId&&ctx.actor(e.target).passivesEnabled?1-p.bonus_magic_resistance/100:1)};},onDamage(ctx,e){const f=ctx.actor(e.target);if(f.heroId!==c.hero.registryNumericId||e.damage<=0||e.source===e.target||e.reflected||e.noReflect||!f.alive||!f.passivesEnabled||ctx.target.distance(e.source,e.target)>scale(p.max_range))return;return {handle:status(ctx,c,e.target,e.source,'skin',p.duration,{dps:p.damage,attackSlow:p.bonus_attack_speed,reflected:true,interval:.25},'basic')};},onStage(ctx,e){if(e.kind==='status-periodic'&&e.key==='skin')return damage(ctx,c,e.source,e.target,p.damage*.25,'magical',{reflected:true,noReflect:true,noLifesteal:true});},projectInterval(ctx,e){let value=0;for(const s of enabledRows(ctx,e.actor,'skin'))value=Math.max(value,s.values.attackSlow);return {attackSlowMax:value};}});}
 if(id==='viper_viper_strike'){positive(p,['duration','projectile_speed']);percent(p,['bonus_movement_speed']);return base(c,FILE,['projectile-request','status','damage'],{planCast:(ctx,e)=>planning(c,ctx,e,{targeted:true}),activate(ctx,e){return {projectile:missile(ctx,c,e,'core4-counter-missile',scale(p.projectile_speed),scale(p.AbilityCastRange)+22,{kind:'viper_strike',reflectionRange:scale(p.AbilityCastRange)+22})};},onContact(ctx,e){return {handle:status(ctx,c,e.source,e.target,'viper_strike',p.duration,{interval:.25,doesBreak:p.does_break===1,dps:p.damage},'none',true)};},onStage(ctx,e){if(e.kind==='status-periodic'&&e.key==='viper_strike')return damage(ctx,c,e.source,e.target,p.damage*.25);if(e.kind==='movement-projection'){let slow=0;for(const s of enabledRows(ctx,e.actor,'viper_strike'))slow=Math.max(slow,p.bonus_movement_speed/100*s.remaining/p.duration);return {moveSlow:slow};}if(e.kind==='break-projection')return {broken:rows(ctx,e.actor,'viper_strike').some(s=>s.remaining>EPS)};},projectInterval(ctx,e){let slow=0;for(const s of enabledRows(ctx,e.actor,'viper_strike'))slow=Math.max(slow,p.bonus_attack_speed*s.remaining/p.duration);return {attackSlowMax:slow};}});}
 throw Error('Unknown Viper selected slot');
}
