import {createBStateSchema} from './state.js';
// Detached per-registry coefficients, never the default content or a private host.
const caches=new WeakMap();
export function model(config){let m=caches.get(config.definitions);if(!m){m={heroes:new Map(),abilities:new Map(),stateSchema:createBStateSchema(),coefficientSchemas:new Map(),maxHp:Math.max(...config.definitions.map(h=>h.combatHp||h.hp*2.8))};for(const h of config.definitions){m.heroes.set(h.registryNumericId,h);for(const a of h.abilities)m.abilities.set(a.id,a);}for(const id of [57,58,62,71,81,82]){const h=m.heroes.get(id);if(!h||!Number.isFinite(h.attributes18?.str)||h.attributes18.str<0||!Number.isFinite(h.attributes18?.agi)||h.attributes18.agi<0||h.move_speed<=0)throw Error('Invalid B derived hero coefficients');}caches.set(config.definitions,m);}return m;}
export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export const number=(n,label)=>{if(!Number.isFinite(n))throw Error('Missing finite B fact: '+label);return n;};
export function coefficient(m,id,key){return number(m.abilities.get(id)?.official?.params?.[key],id+'.'+key);}
export function near(ctx,owner,target,r){const f=ctx.actor(owner),t=ctx.actor(target);return t.alive&&Math.abs(t.x-f.x)<=r+22&&Math.abs(f.y-t.y)<105;}
const recordRequired=['owner','target','abilityId','key','duration','polarity','dispel','pierces','values','handle','effective','remainingSeconds'];
const recordOptional=['intervalSeconds','enabled','statusDeclarationId'];
const isActor=id=>id===0||id===1;
const plain=x=>x!==null&&typeof x==='object'&&!Array.isArray(x)&&Object.getPrototypeOf(x)===Object.prototype;
export function ownedStatusKey(id,key){if(id!=='huskar_burning_spear')return key===id||id==='treant_overgrowth'&&key===id+'_control';if(typeof key!=='string'||!key.startsWith(id+'_'))return false;const n=key.slice(id.length+1);return /^(0|[1-9]\d?)$/.test(n)&&Number(n)<32;}
export function sourceCadence(m,id){switch(id){case'huskar_burning_spear':case'jakiro_dual_breath':case'treant_overgrowth':case'ogre_magi_ignite':return 1;case'jakiro_liquid_fire':return coefficient(m,id,'tick_rate');case'jakiro_macropyre':return coefficient(m,id,'burn_interval');default:return null;}}
function finiteJson(x,depth=0){if(depth>16)return false;if(x===null||typeof x==='boolean'||typeof x==='string')return true;if(typeof x==='number')return Number.isFinite(x);if(Array.isArray(x))return x.length<=128&&x.every(v=>finiteJson(v,depth+1));return plain(x)&&Object.keys(x).length<=64&&Object.values(x).every(v=>finiteJson(v,depth+1));}
const valueFields={huskar_inner_fire:'silence',huskar_burning_spear:'dps',huskar_life_break:'debuffImmune magicReduction slow aspd',night_stalker_void:'slow aspd',night_stalker_crippling_fear:'silence',night_stalker_darkness:'',jakiro_dual_breath:'slow aspd dps',jakiro_liquid_fire:'dps aspd',jakiro_macropyre:'dps',alchemist_acid_spray:'armor',alchemist_unstable_concoction:'',alchemist_corrosive_weaponry:'stacks slow attackReduction',alchemist_chemical_rage:'',treant_natures_grasp:'slow',treant_leech_seed:'disarm',treant_living_armor:'block',treant_overgrowth:'dps disarm',ogre_magi_ignite:'dps slow',ogre_magi_bloodlust:''};
function validateSourceValues(row){if(!Object.hasOwn(valueFields,row.abilityId))return;const numeric=valueFields[row.abilityId].split(' ').filter(Boolean),required=row.abilityId==='jakiro_dual_breath'?['slow','aspd']:row.abilityId==='huskar_life_break'?(row.polarity==='positive'?['debuffImmune','magicReduction']:['slow','aspd']):row.abilityId==='treant_overgrowth'?[row.key===row.abilityId+'_control'?'disarm':'dps']:numeric,allowed=['abilityId',...numeric,...(row.polarity==='negative'?['hostile','polarity']:[]),...(['huskar_life_break','night_stalker_void','ogre_magi_ignite'].includes(row.abilityId)?['reflected','origin']:[])];if(required.some(k=>!Object.hasOwn(row.values,k))||Object.keys(row.values).some(k=>!allowed.includes(k))||numeric.some(k=>row.values[k]!==undefined&&(!Number.isFinite(row.values[k])||Math.abs(row.values[k])>1e7))||row.polarity==='negative'&&(row.values.hostile!==true||row.values.polarity!=='hostile')||row.values.reflected!==undefined&&typeof row.values.reflected!=='boolean'||row.values.origin!==undefined&&!isActor(row.values.origin)||row.values.reflected===true&&!isActor(row.values.origin))throw Error('Invalid B strict source status values');if(row.values.stacks!==undefined&&(!Number.isInteger(row.values.stacks)||row.values.stacks<0||row.values.stacks>64))throw Error('Invalid B strict status stack');}
export function validateStatusRecord(row,target,{allowZero=false}={}){
 if(!plain(row)||recordRequired.some(k=>!Object.hasOwn(row,k))||Object.keys(row).some(k=>!recordRequired.includes(k)&&!recordOptional.includes(k))||!isActor(row.owner)||row.target!==target||!isActor(row.target)||typeof row.abilityId!=='string'||!row.abilityId||typeof row.key!=='string'||!row.key||!Number.isFinite(row.duration)||row.duration<=0||row.duration>3600||!['positive','negative'].includes(row.polarity)||!['basic','strong','none'].includes(row.dispel)||typeof row.pierces!=='boolean'||!plain(row.values)||!finiteJson(row.values)||row.values.abilityId!==row.abilityId||typeof row.handle!=='string'||!row.handle||row.handle.length>256||typeof row.effective!=='boolean'||!Number.isFinite(row.remainingSeconds)||row.remainingSeconds<0||row.remainingSeconds>row.duration||!allowZero&&row.remainingSeconds===0)throw Error('Invalid B strict StatusRecordView');
 if(row.values.dps!==undefined&&(!Number.isFinite(row.values.dps)||row.values.dps<0||row.values.dps>1e7)||row.values.block!==undefined&&(!Number.isFinite(row.values.block)||row.values.block<0))throw Error('Invalid B strict status source values');
 if(row.enabled!==undefined&&(typeof row.enabled!=='boolean'||row.enabled!==row.effective)||row.intervalSeconds!==undefined&&(!Number.isFinite(row.intervalSeconds)||row.intervalSeconds<=0)||row.statusDeclarationId!==undefined&&(typeof row.statusDeclarationId!=='string'||!row.statusDeclarationId))throw Error('Invalid B strict StatusRecordView alias/cadence');
 if(row.polarity==='positive'&&row.owner!==row.target||row.polarity==='negative'&&row.owner===row.target)throw Error('Invalid B status recipient');validateSourceValues(row);return row;
}
function validateSourceDuration(row,m){const p=key=>coefficient(m,row.abilityId,key);let exact=null,maximum=null;switch(row.abilityId){case'huskar_inner_fire':exact=[p('disarm_duration')];break;case'huskar_burning_spear':case'ogre_magi_ignite':case'night_stalker_darkness':case'alchemist_chemical_rage':case'treant_living_armor':case'ogre_magi_bloodlust':exact=[p('duration')];break;case'huskar_life_break':if(row.polarity==='positive')maximum=60;else exact=[p('AbilityDuration')];break;case'night_stalker_void':exact=[p('duration_day'),p('duration_night')];break;case'night_stalker_crippling_fear':exact=[.12];break;case'jakiro_dual_breath':case'jakiro_liquid_fire':exact=[p('AbilityDuration')];break;case'jakiro_macropyre':exact=[p('linger_duration')];break;case'alchemist_acid_spray':exact=[p('tick_rate')+.05];break;case'alchemist_unstable_concoction':exact=[p('brew_time')];break;case'alchemist_corrosive_weaponry':exact=[p('debuff_duration')];break;case'treant_natures_grasp':exact=[.55];break;case'treant_leech_seed':maximum=p('duration');break;case'treant_overgrowth':if(row.key===row.abilityId+'_control')maximum=p('duration');else exact=[p('duration')];break;}if(exact&&!exact.includes(row.duration)||maximum!==null&&row.duration>maximum)throw Error('Unadmitted B status source lifetime');}
function authorizeRecord(row,scope,key){const expected=scope.id===row.abilityId?scope.id:scope.contract.readonlyCrossKeys.includes(key)?key:null;if(expected!==row.abilityId||expected===scope.id&&!ownedStatusKey(scope.id,key)||expected!==scope.id&&row.polarity!=='positive')throw Error('Unauthorized B status record identity');}
export function queryStatuses(ctx,target,key,scope){if(scope.contract.mode==='strict'&&!ownedStatusKey(scope.id,key)&&!scope.contract.readonlyCrossKeys.includes(key))throw Error('Unauthorized B readonly status query');const rows=ctx.status.query(target,key);if(scope.contract.mode!=='strict')return rows;if(!Array.isArray(rows)||rows.length>64)throw Error('Invalid B strict query list');const handles=new Set();for(const row of rows){validateStatusRecord(row,target);if(row.key!==key||handles.has(row.handle))throw Error('Mismatched B status query key/handle');authorizeRecord(row,scope,key);validateSourceDuration(row,scope.m);if(row.values.dps!==undefined&&row.intervalSeconds!==sourceCadence(scope.m,row.abilityId))throw Error('Unadmitted B query source cadence');handles.add(row.handle);}return rows;}
export function active(status,actor,mode='legacy'){if(mode==='strict'){validateStatusRecord(status,actor.id,{allowZero:true});return status.effective&&status.remainingSeconds>0;}return status.enabled===true||(status.enabled===undefined&&(status.polarity==='positive'||!actor.invulnerable&&(status.pierces||!actor.debuffImmune)));}
export function positive(ctx,actor,key,scope){const f=ctx.actor(actor);return queryStatuses(ctx,actor,key,scope).find(s=>s.target===actor&&s.polarity==='positive'&&active(s,f,scope.contract.mode));}
export function statuses(event,actor,scope){if(!Array.isArray(event.statuses))throw Error('Missing B readonly status facts');if(scope.contract.mode==='strict'){if(event.statuses.length>64)throw Error('Invalid B strict status list');const handles=new Set();for(const row of event.statuses){validateStatusRecord(row,actor.id);if(handles.has(row.handle))throw Error('Duplicate B status list handle');handles.add(row.handle);if(row.abilityId===scope.id){if(!ownedStatusKey(scope.id,row.key))throw Error('Unauthorized B status list key');validateSourceDuration(row,scope.m);}}}return event.statuses.filter(s=>s.target===actor.id&&active(s,actor,scope.contract.mode));}
export function validatePeriodic(event,scope){if(scope.contract.mode!=='strict')return;if(!plain(event)||Object.keys(event).sort().join(',')!=='actor,enabled,intervalSeconds,kind,status'||event.kind!=='status-periodic'||!isActor(event.actor)||typeof event.enabled!=='boolean')throw Error('Invalid B strict periodic payload');const row=validateStatusRecord(event.status,event.actor,{allowZero:true});if(row.abilityId!==scope.id||!ownedStatusKey(scope.id,row.key)||row.effective!==event.enabled)throw Error('Mismatched B strict periodic identity/effectiveness');validateSourceDuration(row,scope.m);const cadence=sourceCadence(scope.m,scope.id);if(cadence===null||row.intervalSeconds!==cadence||event.intervalSeconds!==cadence)throw Error('Unadmitted B periodic source cadence');}
export function baseSpeed(m,actor){const h=m.heroes.get(actor.heroId);return 100+(h.attributes18?.agi??h.level18?.agility??0);}
export function plan(ctx,facts,definition){const m=definition.mvp,f=ctx.actor(facts.owner),t=ctx.actor(facts.target);let ok=facts.actionReady===true&&!m.passive&&f.alive&&!f.silenced&&facts.cooldownRemaining<=1e-8&&facts.manaAvailable>=m.mana;
 if(definition.id==='huskar_life_break'&&f.rooted)ok=false;
 if(['huskar_life_break','night_stalker_void','ogre_magi_fireblast','ogre_magi_ignite'].includes(definition.id)&&(!t.alive||t.invulnerable||Math.abs(t.x-f.x)>m.range_wu+22))ok=false;
 if(definition.id==='jakiro_dual_breath'&&(t.invulnerable||!near(ctx,facts.owner,facts.target,m.range_wu)))ok=false;
 if(['jakiro_ice_path','jakiro_macropyre','alchemist_acid_spray','treant_natures_grasp'].includes(definition.id)&&(!Number.isFinite(facts.aimX)||facts.aimX<45||facts.aimX>1155||Math.abs(facts.aimX-f.x)>m.range_wu+22))ok=false;
 return {accepted:ok,...(!ok?{reason:m.passive?'passive':'not-admitted'}:{}),manaCost:m.mana,cooldownSeconds:m.cooldown_s,chargeCost:0,windupSeconds:m.startup_frames/60,recoverySeconds:m.recovery_frames/60,action:'cast'};}
export const reflection=route=>route.reflected?{reflected:true,origin:route.originalOwner}:{};
export function damage(ctx,id,source,target,amount,type='magical',reflected=false){return ctx.damage({source,target,abilityId:id,amount,type,dot:true,blockable:false,reflected,noReflect:reflected,noLifesteal:reflected});}
export function status(ctx,id,owner,target,duration,values={},options={}){return ctx.status.apply({owner,target,abilityId:id,key:options.key??id,duration,polarity:options.positive?'positive':'negative',dispel:options.dispel??'basic',pierces:options.pierces??false,values:{abilityId:id,...(!options.positive?{hostile:true,polarity:'hostile'}:{}),...values},...(options.interval?{intervalSeconds:options.interval}:{} )});}
export function buff(ctx,id,owner,duration,values={}){return status(ctx,id,owner,owner,duration,values,{positive:true,dispel:id==='huskar_life_break'?'none':'basic'});}
export function control(ctx,id,owner,target,type,duration,pierces=false){return ctx.control.apply({owner,target,abilityId:id,key:id,type,duration,pierces,dispel:'strong'});}
export function route(ctx,id,cast,range,rangePolicy='admission-and-delivery'){if(!Number.isFinite(range)||range<0||!['admission-and-delivery','admission-only'].includes(rangePolicy))throw Error('Invalid B target range policy');return ctx.target.route({owner:cast.owner,target:cast.target,abilityId:id,range,reflectable:true,reflected:cast.reflected===true,...(rangePolicy==='admission-only'?{rangePolicy}:{})});}
export function immediateMove(ctx,id,actor,castId,destinationX){return ctx.motion({actor,abilityId:id,castId,kind:'dash',destinationX,speed:0,duration:0});}
export function combineInterval(baseSeconds,baseAttackSpeed,contributions){let attackSpeed=0,baseAttackTime=null;for(const c of contributions){attackSpeed+=number(c.attackSpeed??0,'attack speed');if(c.baseAttackTime!==undefined)baseAttackTime=number(c.baseAttackTime,'base attack time');}const raw=baseAttackTime===null?baseSeconds:baseAttackTime*100/baseAttackSpeed;return raw*baseAttackSpeed/clamp(baseAttackSpeed+attackSpeed,20,700);}
export function combineAttack(baseAttack,contributions){let bonus=0,reduction=0;for(const c of contributions){bonus+=number(c.attackBonus??0,'attack bonus');reduction+=number(c.baseAttackReduction??0,'base attack reduction');}return Math.max(0,baseAttack+bonus-baseAttack*clamp(reduction,0,1));}
export function combineMovement(contributions){let bonus=0,slow=0;for(const c of contributions){bonus+=number(c.moveBonus??0,'move bonus');slow+=number(c.slow??0,'slow');}return(1+bonus)*(1-clamp(slow,0,1));}
const exactKeys=(value,keys)=>plain(value)&&Object.keys(value).sort().join(',')===keys.slice().sort().join(',');
export function validateRefreshResult(result,scope,target){if(scope.contract.mode!=='strict')return result;const r=result?.statusRefresh;if(scope.id!=='jakiro_macropyre'||!exactKeys(result,['statusRefresh'])||!exactKeys(r,['target','key','duration','resetElapsed','preserveTick'])||r.target!==target||!isActor(target)||r.key!==scope.id||!Number.isFinite(r.duration)||r.duration<0||r.duration!==coefficient(scope.m,scope.id,'linger_duration')||r.resetElapsed!==true||r.preserveTick!==true)throw Error('Invalid B strict statusRefresh');return result;}
export function validateBlockResult(result,scope,target){if(scope.contract.mode!=='strict')return result;const r=result?.statusBlockUpdate;if(scope.id!=='treant_living_armor'||!exactKeys(result,['damage','statusBlockUpdate'])||!exactKeys(r,['target','key','remainingBlock','removeAtZero'])||r.target!==target||!isActor(target)||r.key!==scope.id||!Number.isFinite(result.damage)||result.damage<0||!Number.isFinite(r.remainingBlock)||r.removeAtZero!==true)throw Error('Invalid B strict statusBlockUpdate');return result;}
