import {model,coefficient as coefficientOf,number,clamp,near,positive as positiveOf,statuses as statusesOf,queryStatuses,validatePeriodic,validateRefreshResult,validateBlockResult,ownedStatusKey,baseSpeed,plan,reflection,damage as damageOf,status,buff,control,route,immediateMove} from './model.js';
import {executionParameters,readOwner,writeOwner,toggle,remember,forget} from './state.js';
import {codeIdentity,defineStateSchema} from '../../index.js';
const AREAS=new Set(['night_stalker_crippling_fear','jakiro_ice_path','jakiro_macropyre','alchemist_acid_spray','treant_natures_grasp']);
const PERIODIC=new Set(['huskar_burning_spear','huskar_life_break','night_stalker_void','jakiro_dual_breath','jakiro_liquid_fire','jakiro_macropyre','treant_overgrowth','ogre_magi_ignite']);
const SLOW=new Set(['huskar_life_break','night_stalker_void','jakiro_dual_breath','alchemist_corrosive_weaponry','treant_natures_grasp','ogre_magi_ignite']);
const ASPD=new Set(['huskar_life_break','night_stalker_void','jakiro_dual_breath','jakiro_liquid_fire']);
const PARAMS={
 huskar_inner_fire:'health_cost damage radius disarm_duration knockback_distance',huskar_burning_spear:'max_health_cost burn_damage burn_damage_max_pct duration',huskar_berserkers_blood:'hp_threshold_max maximum_attack_speed maximum_magic_resist maximum_health_regen',huskar_life_break:'charge_speed immunity_resist health_cost_percent health_damage AbilityDuration movespeed attack_speed',
 night_stalker_void:'damage duration_night duration_day movespeed_slow attackspeed_slow',night_stalker_crippling_fear:'radius duration_night duration_day tick_rate dps',night_stalker_midnight_feast:'attack_heal',night_stalker_darkness:'duration bonus_damage',
 jakiro_dual_breath:'AbilityDuration fire_delay burn_damage',jakiro_ice_path:'path_delay path_radius path_duration damage stun_duration',jakiro_liquid_fire:'AbilityDuration damage slow_attack_speed_pct tick_rate',jakiro_macropyre:'path_width duration burn_interval linger_duration damage',
 alchemist_acid_spray:'radius duration tick_rate armor_reduction damage',alchemist_unstable_concoction:'brew_time brew_explosion max_damage max_stun move_speed',alchemist_corrosive_weaponry:'max_stacks stacks_per_attack debuff_duration slow_per_stack attack_dmg_per_stack',alchemist_chemical_rage:'duration base_attack_time bonus_movespeed bonus_health_regen',
 treant_natures_grasp:'latch_range vines_duration movement_slow damage_per_second',treant_leech_seed:'leech_damage duration flat_heal leech_heal healing_pulse_count',treant_living_armor:'duration damage_block_base damage_block_threshold damage_block_loss heal_per_second',treant_overgrowth:'radius duration damage',
 ogre_magi_fireblast:'fireblast_damage stun_duration multicast_delay',ogre_magi_ignite:'duration burn_damage slow_movement_speed_pct multicast_delay',ogre_magi_bloodlust:'duration self_bonus bonus_movement_speed',ogre_magi_multicast:'strength_for_one_pct multicast_4_times multicast_3_times multicast_2_times'
};
const signed=new Set(['movespeed','slow_attack_speed_pct','slow_movement_speed_pct']);
const lifetimes=new Set(['duration','duration_day','duration_night','AbilityDuration','disarm_duration','path_duration','linger_duration','vines_duration','debuff_duration','stun_duration','max_stun']);
const timings=new Set(['brew_time','brew_explosion','fire_delay','path_delay','multicast_delay','base_attack_time']);
const intervals=new Set(['tick_rate','burn_interval']);
const percent=new Set(['max_health_cost','burn_damage_max_pct','maximum_magic_resist','immunity_resist','slow_per_stack','attack_dmg_per_stack','movement_slow','movespeed_slow','bonus_movement_speed','leech_heal']);
export function bCoefficientSchema(id){const properties={};for(const key of (PARAMS[id]??'').split(' ')){let minimum=signed.has(key)?-100:0,maximum=signed.has(key)?100:1e6,type='number';if(lifetimes.has(key)||timings.has(key)){minimum=.001;maximum=60;}if(intervals.has(key)){minimum=.001;maximum=60;}if(percent.has(key))maximum=100;if(['health_cost_percent','health_damage'].includes(key))maximum=1;if(key==='hp_threshold_max')maximum=99;if(['charge_speed','strength_for_one_pct'].includes(key))minimum=.001;if(key==='max_stacks'||key==='stacks_per_attack'){type='integer';minimum=1;maximum=64;}if(key==='healing_pulse_count'){type='integer';maximum=64;}if(['radius','path_radius','path_width','latch_range','knockback_distance'].includes(key))maximum=10000;properties[key]={type,minimum,maximum};}return defineStateSchema({id:'heros/b-coefficients/'+id,version:'2.0.0',schema:{type:'object',properties,required:Object.keys(properties),additionalProperties:false}});}
function validateCoefficients(m,id,p,a){const values=Object.fromEntries(PARAMS[id].split(' ').map(key=>[key,p(key)]));let schema=m.coefficientSchemas.get(id);if(!schema){schema=bCoefficientSchema(id);m.coefficientSchemas.set(id,schema);}if(!schema.validate(values))throw Error('Invalid B coefficient schema '+id);
 const maxHp=m.maxHp;
 if(id==='huskar_burning_spear'&&p('burn_damage')+maxHp*p('burn_damage_max_pct')/100>1e7)throw Error('B derived Spear damage overflow');
 if(id==='huskar_life_break'&&(maxHp*Math.max(p('health_damage'),p('health_cost_percent'))>1e7||Math.min(a.mvp.range_wu+22,1110)/(p('charge_speed')*.55)+.05>60))throw Error('B derived Life Break damage/travel overflow');
 if(id==='alchemist_unstable_concoction'&&p('brew_explosion')<p('brew_time'))throw Error('B explosion before brew');
 if(id==='alchemist_corrosive_weaponry'&&p('stacks_per_attack')>p('max_stacks'))throw Error('Invalid B stack increment');
 if(id==='treant_leech_seed'&&p('flat_heal')+maxHp*p('leech_heal')/100>1e7)throw Error('B derived Seed healing overflow');
 if(id==='huskar_berserkers_blood'&&m.heroes.get(57).attributes18.str*p('maximum_health_regen')/100>1e7)throw Error('B derived Blood healing overflow');
 for(const [rate,interval] of [['burn_damage','tick_rate'],['damage','tick_rate'],['damage','burn_interval'],['dps','tick_rate']])if(rate in values&&interval in values&&values[rate]*values[interval]>1e7)throw Error('B periodic damage overflow');
}
export function createBRule(config){
 const m=model(config),a=config.definition,id=a.id,p=key=>coefficientOf(m,id,key);
 validateCoefficients(m,id,p,a);
 const execution=executionParameters(config),damage=(ctx,id,source,target,amount,...rest)=>damageOf(ctx,id,source,target,amount*execution.damageScale,...rest),heal=(ctx,spec)=>ctx.heal({...spec,amount:spec.amount*execution.healScale});
 const scope={m,id,contract:execution.statusContract},positive=(ctx,actor,key)=>positiveOf(ctx,actor,key,scope),query=(ctx,target,key)=>queryStatuses(ctx,target,key,scope);
 const impl={behaviorId:'b-v6/'+id,revision:'2.3.1',...codeIdentity(['rules/b/model.js','rules/b/programs.js','rules/b/register.js','rules/b/state.js']),namespace:'heros/b/'+id,requires:[],stateSchema:m.stateSchema,planCast:(ctx,facts)=>plan(ctx,facts,a)};
 const requireCaps=(...caps)=>{impl.requires.push(...caps);};
 const aliveOwner=(ctx,event)=>ctx.actor(event.actor??event.owner).alive;
 const ownStatus=(ctx,event)=>statusesOf(event,ctx.actor(event.actor),scope).filter(s=>s.abilityId===id||s.values?.abilityId===id);
 const schedule=(ctx,owner,target,handler,delay,castId,payload={})=>{const h=ctx.schedule({abilityId:id,owner,handler,delay,data:{owner,target,castId,payload}});remember(ctx,owner,'jobs',h);return h;};
 const jobStart=(ctx,d)=>{if(typeof d.handle!=='string')throw Error('Missing B scheduled handle fact');forget(ctx,d.owner,'jobs',d.handle);return ctx.actor(d.owner).alive&&(d.target===null||ctx.actor(d.target).alive);};
 const removeKey=(ctx,target,key)=>{if(scope.contract.mode==='strict'&&!ownedStatusKey(id,key))throw Error('Unauthorized B status removal');for(const s of query(ctx,target,key)){if(typeof s.handle!=='string')throw Error('Missing B status handle fact');ctx.status.remove(s.handle);}};
 const spawnArea=(ctx,c,x,radius,duration,interval,follow=false,oneHit=false)=>{const h=ctx.legacyEffect.spawn({owner:c.owner,abilityId:id,castId:c.castId,kind:'area',x,radius,duration,data:{intervalSeconds:interval,follow,oneHit}});remember(ctx,c.owner,'areas',h);};
 switch(id){
 case 'huskar_inner_fire':requireCaps('self-damage','damage','status','motion-request');impl.activate=(ctx,c)=>{const f=ctx.actor(c.owner),t=ctx.actor(c.target);ctx.selfDamage({actor:c.owner,abilityId:id,amount:p('health_cost'),nonlethal:true});if(near(ctx,c.owner,c.target,p('radius')*.55)){damage(ctx,id,c.owner,c.target,p('damage'));if(status(ctx,id,c.owner,c.target,p('disarm_duration'),{silence:1}))immediateMove(ctx,id,c.target,c.castId,f.x+Math.sign(t.x-f.x||1)*p('knockback_distance')*.55);}};break;
 case 'huskar_burning_spear':requireCaps('self-damage','status','damage');impl.activate=(ctx,c)=>toggle(ctx,c.owner);impl.onAttack=(ctx,e)=>{const f=ctx.actor(e.actor),t=ctx.actor(e.target),s=readOwner(ctx,e.actor);if(!e.landed||f.heroId!==57||!f.alive||!t.alive||!s.toggle)return;ctx.selfDamage({actor:e.actor,abilityId:id,amount:f.maxHp*p('max_health_cost')/100,nonlethal:true});status(ctx,id,e.actor,e.target,p('duration'),{dps:p('burn_damage')+t.maxHp*p('burn_damage_max_pct')/100},{key:id+'_'+s.sequence,interval:1});writeOwner(ctx,e.actor,{...s,sequence:(s.sequence+1)%32});};break;
 case 'huskar_berserkers_blood':{requireCaps('heal');const blood=(ctx,actor)=>{const f=ctx.actor(actor);return f.heroId===57&&f.passivesEnabled?clamp((1-f.hp/f.maxHp)/(1-p('hp_threshold_max')/100),0,1):0;};impl.projectInterval=(ctx,e)=>({attackSpeed:blood(ctx,e.actor)*p('maximum_attack_speed')});impl.projectDamage=(ctx,e)=>({magicalMultiplier:e.stage==='modify'&&e.damageType==='magical'?1-blood(ctx,e.target)*p('maximum_magic_resist')/100:1});impl.onStage=(ctx,e)=>{const f=ctx.actor(e.actor);if(e.kind==='passive-continuous'&&f.alive&&f.heroId===57)heal(ctx,{source:e.actor,target:e.actor,abilityId:id,amount:m.heroes.get(f.heroId).attributes18.str*p('maximum_health_regen')/100*blood(ctx,e.actor)*number(e.elapsedSeconds,'elapsed seconds')});};break;}
 case 'huskar_life_break':requireCaps('status','target-route','schedule','self-damage','damage','motion-request');impl.activate=(ctx,c)=>{const r=route(ctx,id,c,a.mvp.range_wu,'admission-only');if(!r.accepted)return;ctx.status.cleanse(r.owner,'basic',id);const travel=ctx.target.distance(r.owner,r.target)/(p('charge_speed')*.55);buff(ctx,id,r.owner,travel+.05,{debuffImmune:1,magicReduction:p('immunity_resist')/100,...reflection(r)});schedule(ctx,r.owner,r.target,'release',travel,c.castId,reflection(r));return{recoveryFloor:{actor:r.owner,seconds:travel}};};impl.scheduledHandlers={release(ctx,d){if(!jobStart(ctx,d))return;removeKey(ctx,d.owner,id);const f=ctx.actor(d.owner),t=ctx.actor(d.target);if(t.invulnerable)return;immediateMove(ctx,id,d.owner,d.castId,t.x-Math.sign(t.x-f.x||1)*40);ctx.selfDamage({actor:d.owner,abilityId:id,amount:f.hp*p('health_cost_percent'),nonlethal:true});damage(ctx,id,d.owner,d.target,t.hp*p('health_damage'),'magical',d.payload.reflected===true);status(ctx,id,d.owner,d.target,p('AbilityDuration'),{slow:-p('movespeed')/100,aspd:-p('attack_speed'),...d.payload});}};impl.projectDamage=(ctx,e)=>({magicalMultiplier:e.stage==='modify'&&e.damageType==='magical'?1-ownStatus(ctx,{...e,actor:e.target}).reduce((n,s)=>n+(s.values.magicReduction??0),0):1});break;
 case 'night_stalker_void':requireCaps('status','damage','target-route','control');impl.activate=(ctx,c)=>{if(!near(ctx,c.owner,c.target,a.mvp.range_wu))return;const night=!!positive(ctx,c.owner,'night_stalker_darkness'),r=route(ctx,id,c,a.mvp.range_wu);if(!r.accepted)return;damage(ctx,id,r.owner,r.target,p('damage'),'magical',r.reflected);status(ctx,id,r.owner,r.target,p(night?'duration_night':'duration_day'),{slow:p('movespeed_slow')/100,aspd:-p('attackspeed_slow'),...reflection(r)});if(night)control(ctx,id,r.owner,r.target,'stun',.1);};break;
 case 'night_stalker_crippling_fear':requireCaps('legacy-effect','status','damage');impl.activate=(ctx,c)=>spawnArea(ctx,c,ctx.actor(c.owner).x,p('radius')*.55,p(positive(ctx,c.owner,'night_stalker_darkness')?'duration_night':'duration_day'),p('tick_rate'),true);impl.onContact=(ctx,e)=>{if(e.kind==='area-exit')return removeKey(ctx,e.target,id);if(e.kind==='area-pulse'&&ctx.actor(e.actor).alive&&status(ctx,id,e.actor,e.target,.12,{silence:1}))damage(ctx,id,e.actor,e.target,p('dps')*number(e.intervalSeconds,'area interval'));};break;
 case 'night_stalker_midnight_feast':requireCaps('heal');impl.onAttack=(ctx,e)=>{const f=ctx.actor(e.actor);if(e.landed&&f.alive&&f.heroId===58&&f.passivesEnabled)heal(ctx,{source:e.actor,target:e.actor,abilityId:id,amount:p('attack_heal')});};break;
 case 'night_stalker_darkness':requireCaps('status');impl.activate=(ctx,c)=>buff(ctx,id,c.owner,p('duration'));impl.projectAttack=(ctx,e)=>({attackBonus:ownStatus(ctx,e).some(s=>s.polarity==='positive')?p('bonus_damage'):0});break;
 case 'jakiro_dual_breath':requireCaps('status','schedule','damage');impl.activate=(ctx,c)=>{if(near(ctx,c.owner,c.target,a.mvp.range_wu)){status(ctx,id,c.owner,c.target,p('AbilityDuration'),{slow:.4,aspd:-40});schedule(ctx,c.owner,c.target,'release',p('fire_delay'),c.castId);}};impl.scheduledHandlers={release(ctx,d){if(jobStart(ctx,d)&&near(ctx,d.owner,d.target,a.mvp.range_wu))status(ctx,id,d.owner,d.target,p('AbilityDuration'),{slow:.4,aspd:-40,dps:p('burn_damage')},{interval:1});}};break;
 case 'jakiro_ice_path':requireCaps('schedule','legacy-effect','damage','control');impl.activate=(ctx,c)=>{const x=ctx.actor(c.owner).x;schedule(ctx,c.owner,null,'release',p('path_delay'),c.castId,{origin:x,aim:clamp(c.aimX,x-a.mvp.range_wu,x+a.mvp.range_wu)});};impl.scheduledHandlers={release(ctx,d){if(!jobStart(ctx,d))return;const end=d.payload.aim;spawnArea(ctx,{owner:d.owner,castId:d.castId},(d.payload.origin+end)/2,Math.abs(end-d.payload.origin)/2+p('path_radius')*.55,p('path_duration'),0,false,true);}};impl.onContact=(ctx,e)=>{if(e.kind==='area-contact'&&e.firstContact===true&&ctx.actor(e.actor).alive){damage(ctx,id,e.actor,e.target,p('damage'));control(ctx,id,e.actor,e.target,'stun',p('stun_duration'));}};break;
 case 'jakiro_liquid_fire':requireCaps('status','damage');impl.activate=(ctx,c)=>{const s=readOwner(ctx,c.owner);writeOwner(ctx,c.owner,{...s,toggle:true});};impl.onAttack=(ctx,e)=>{const s=readOwner(ctx,e.actor);if(e.landed&&ctx.actor(e.actor).heroId===62&&ctx.actor(e.actor).alive&&s.toggle){writeOwner(ctx,e.actor,{...s,toggle:false});status(ctx,id,e.actor,e.target,p('AbilityDuration'),{dps:p('damage'),aspd:p('slow_attack_speed_pct')},{interval:p('tick_rate')});}};break;
 case 'jakiro_macropyre':requireCaps('legacy-effect','status','damage');impl.activate=(ctx,c)=>{const x=ctx.actor(c.owner).x,end=clamp(c.aimX,x-a.mvp.range_wu,x+a.mvp.range_wu);spawnArea(ctx,c,(x+end)/2,Math.abs(end-x)/2+p('path_width')*.275,p('duration'),p('burn_interval'));};impl.onContact=(ctx,e)=>{if(e.kind!=='area-pulse'||!ctx.actor(e.actor).alive)return;const old=query(ctx,e.target,id)[0];if(old)return validateRefreshResult({statusRefresh:{target:e.target,key:id,duration:p('linger_duration'),resetElapsed:true,preserveTick:true}},scope,e.target);status(ctx,id,e.actor,e.target,p('linger_duration'),{dps:p('damage')},{interval:p('burn_interval')});};break;
 case 'alchemist_acid_spray':requireCaps('legacy-effect','status','damage');impl.activate=(ctx,c)=>spawnArea(ctx,c,c.aimX,p('radius')*.55,p('duration'),p('tick_rate'));impl.onContact=(ctx,e)=>{if(e.kind==='area-pulse'&&ctx.actor(e.actor).alive){status(ctx,id,e.actor,e.target,number(e.intervalSeconds,'area interval')+.05,{armor:-p('armor_reduction')});damage(ctx,id,e.actor,e.target,p('damage')*e.intervalSeconds,'physical');}};impl.projectDamage=(ctx,e)=>({sharedArmorDelta:e.stage==='modify'&&e.damageType==='physical'?ownStatus(ctx,{...e,actor:e.target}).reduce((n,s)=>n+(s.values.armor??0),0):0});break;
 case 'alchemist_unstable_concoction':requireCaps('status','schedule','damage','control','target-route','cue');impl.activate=(ctx,c)=>{buff(ctx,id,c.owner,p('brew_time'));schedule(ctx,c.owner,null,'release',p('brew_time'),c.castId);};impl.scheduledHandlers={release(ctx,d){if(!jobStart(ctx,d))return;removeKey(ctx,d.owner,id);if(d.payload.self){damage(ctx,id,d.owner,d.owner,p('max_damage'),'physical');control(ctx,id,d.owner,d.owner,'stun',p('max_stun'));}else if(!ctx.actor(d.target??1-d.owner).invulnerable&&near(ctx,d.owner,d.target??1-d.owner,a.mvp.range_wu)){ctx.cue({kind:'targeted-hit',abilityId:id,actor:d.owner,target:d.target??1-d.owner});const r=route(ctx,id,{owner:d.owner,target:d.target??1-d.owner,reflected:false},a.mvp.range_wu);if(!r.accepted)return;damage(ctx,id,r.owner,r.target,p('max_damage'),'physical',r.reflected);control(ctx,id,r.owner,r.target,'stun',p('max_stun'));}else schedule(ctx,d.owner,d.target,'release',p('brew_explosion')-p('brew_time'),d.castId,{self:true});}};impl.projectInterval=(ctx,e)=>({moveBonus:ownStatus(ctx,e).some(s=>s.polarity==='positive')?p('move_speed')/100:0});break;
 case 'alchemist_corrosive_weaponry':requireCaps('status');impl.onAttack=(ctx,e)=>{const f=ctx.actor(e.actor);if(!e.landed||!f.alive||f.heroId!==71||!f.passivesEnabled)return;const old=query(ctx,e.target,id)[0],stacks=Math.min(p('max_stacks'),(old?.values.stacks??0)+p('stacks_per_attack'));status(ctx,id,e.actor,e.target,p('debuff_duration'),{stacks,slow:stacks*p('slow_per_stack')/100,attackReduction:stacks*p('attack_dmg_per_stack')/100});};impl.projectAttack=(ctx,e)=>({baseAttackReduction:ownStatus(ctx,e).reduce((n,s)=>n+(s.values.attackReduction??0),0)});break;
 case 'alchemist_chemical_rage':requireCaps('status','heal');impl.activate=(ctx,c)=>{ctx.status.cleanse(c.owner,'basic',id);buff(ctx,id,c.owner,p('duration'));};impl.projectInterval=(ctx,e)=>{const f=ctx.actor(e.actor),on=ownStatus(ctx,e).some(s=>s.polarity==='positive');return on?{baseAttackTime:p('base_attack_time'),moveBonus:p('bonus_movespeed')*.8/m.heroes.get(f.heroId).move_speed}:{ };};impl.onStage=(ctx,e)=>{if(e.kind==='continuous'&&ctx.actor(e.actor).alive&&ownStatus(ctx,e).length)heal(ctx,{source:e.actor,target:e.actor,abilityId:id,amount:p('bonus_health_regen')*number(e.elapsedSeconds,'live elapsed')});};break;
 case 'treant_natures_grasp':requireCaps('legacy-effect','status','damage');impl.activate=(ctx,c)=>{const x=ctx.actor(c.owner).x,end=clamp(c.aimX,x-a.mvp.range_wu,x+a.mvp.range_wu);spawnArea(ctx,c,(x+end)/2,Math.abs(end-x)/2+p('latch_range')*.55,p('vines_duration'),.5);};impl.onContact=(ctx,e)=>{if(e.kind==='area-pulse'&&ctx.actor(e.actor).alive&&status(ctx,id,e.actor,e.target,number(e.intervalSeconds,'area interval')+.05,{slow:p('movement_slow')/100}))damage(ctx,id,e.actor,e.target,p('damage_per_second')*e.intervalSeconds);};break;
 case 'treant_leech_seed':requireCaps('damage','status','control','heal','schedule');impl.activate=(ctx,c)=>{const s=readOwner(ctx,c.owner);writeOwner(ctx,c.owner,{...s,toggle:true});};impl.onDamage=(ctx,e)=>{const f=ctx.actor(e.actor),s=readOwner(ctx,e.actor);if(f.heroId!==81||!s.toggle||!e.basic||e.guarded||e.reflected||e.actor===e.target||number(e.actual,'actual debit')<=0)return;writeOwner(ctx,e.actor,{...s,toggle:false});damage(ctx,id,e.actor,e.target,p('leech_damage'));const cc=control(ctx,id,e.actor,e.target,'root',p('duration'));if(cc)status(ctx,id,e.actor,e.target,cc.duration,{disarm:1},{dispel:'strong'});const amount=p('flat_heal')+e.actual*p('leech_heal')/100;for(let i=1;i<=p('healing_pulse_count');i++)schedule(ctx,e.actor,null,'heal',i*.5,e.attackHandle,{amount});};impl.scheduledHandlers={heal(ctx,d){if(jobStart(ctx,d))heal(ctx,{source:d.owner,target:d.owner,abilityId:id,amount:d.payload.amount});}};break;
 case 'treant_living_armor':requireCaps('status','heal');impl.activate=(ctx,c)=>buff(ctx,id,c.owner,p('duration'),{block:p('damage_block_base')});impl.projectDamage=(ctx,e)=>{if(e.stage!=='before-debit')return{};if(scope.contract.mode==='strict'&&(!Number.isFinite(e.amount)||e.amount<0))throw Error('Invalid B strict damage fact');const s=ownStatus(ctx,{...e,actor:e.target}).find(s=>s.polarity==='positive');if(!s||e.amount<p('damage_block_threshold'))return{};const block=number(s.values.block,'living armor block');return validateBlockResult({damage:Math.max(0,e.amount-block),statusBlockUpdate:{target:e.target,key:id,remainingBlock:block-p('damage_block_loss'),removeAtZero:true}},scope,e.target);};impl.onStage=(ctx,e)=>{if(e.kind==='continuous'&&ctx.actor(e.actor).alive&&ownStatus(ctx,e).length)heal(ctx,{source:e.actor,target:e.actor,abilityId:id,amount:p('heal_per_second')*number(e.elapsedSeconds,'live elapsed')});};break;
 case 'treant_overgrowth':requireCaps('status','damage','control');impl.activate=(ctx,c)=>{if(near(ctx,c.owner,c.target,p('radius')*.55)){status(ctx,id,c.owner,c.target,p('duration'),{dps:p('damage')},{dispel:'strong',pierces:true,interval:1});const cc=control(ctx,id,c.owner,c.target,'root',p('duration'),true);if(cc)status(ctx,id,c.owner,c.target,cc.duration,{disarm:1},{key:id+'_control',dispel:'strong',pierces:true});}};break;
 case 'ogre_magi_fireblast':case 'ogre_magi_ignite':{requireCaps('status','target-route','damage','control','schedule');const deliver=(ctx,owner,target)=>{const r=route(ctx,id,{owner,target,reflected:false},a.mvp.range_wu,'admission-only');if(!r.accepted)return;if(id==='ogre_magi_fireblast'){damage(ctx,id,r.owner,r.target,p('fireblast_damage'),'magical',r.reflected);control(ctx,id,r.owner,r.target,'stun',p('stun_duration'));}else status(ctx,id,r.owner,r.target,p('duration'),{dps:p('burn_damage'),slow:-p('slow_movement_speed_pct')/100,...reflection(r)},{interval:1});};impl.activate=(ctx,c)=>{if(!Number.isInteger(c.multicastCount)||c.multicastCount<1||c.multicastCount>4)throw Error('Missing B committed multicast fact');if(!ctx.actor(c.target).alive||ctx.actor(c.target).invulnerable)return;deliver(ctx,c.owner,c.target);for(let i=1;i<c.multicastCount;i++)schedule(ctx,c.owner,c.target,'pulse',i*p('multicast_delay'),c.castId);};impl.scheduledHandlers={pulse(ctx,d){if(jobStart(ctx,d))deliver(ctx,d.owner,d.target);}};break;}
 case 'ogre_magi_bloodlust':requireCaps('status');impl.activate=(ctx,c)=>buff(ctx,id,c.owner,p('duration'));impl.projectInterval=(ctx,e)=>ownStatus(ctx,e).some(s=>s.polarity==='positive')?{attackSpeed:p('self_bonus'),moveBonus:p('bonus_movement_speed')/100}:{};break;
 case 'ogre_magi_multicast':impl.onCastCommitted=(ctx,e)=>{if(!['ogre_magi_fireblast','ogre_magi_ignite'].includes(e.castAbilityId))return{multicastCount:1};const f=ctx.actor(e.actor);if(!f.passivesEnabled)return{multicastCount:1};const roll=ctx.random()*100,bonus=m.heroes.get(f.heroId).attributes18.str/p('strength_for_one_pct');return{multicastCount:roll<p('multicast_4_times')+bonus?4:roll<p('multicast_3_times')+bonus?3:roll<p('multicast_2_times')+bonus?2:1};};break;
 default:throw Error('Unowned B skill '+id);
 }
 if(ASPD.has(id)){requireCaps('status');const prior=impl.projectInterval;impl.projectInterval=(ctx,e)=>({...prior?.(ctx,e),attackSpeed:ownStatus(ctx,e).reduce((n,s)=>n+(s.values.aspd??0),0)});}
 if(SLOW.has(id)){requireCaps('status');const prior=impl.projectInterval;impl.projectInterval=(ctx,e)=>({...prior?.(ctx,e),slow:ownStatus(ctx,e).reduce((n,s)=>n+(s.values.slow??0),0)});}
 if(id==='huskar_inner_fire'||id==='night_stalker_crippling_fear'||id==='treant_overgrowth'||id==='treant_leech_seed'){requireCaps('status');const prior=impl.projectInterval;impl.projectInterval=(ctx,e)=>({...prior?.(ctx,e),silenced:ownStatus(ctx,e).some(s=>s.values.silence>0),disarmed:ownStatus(ctx,e).some(s=>s.values.disarm>0)});}
 if(PERIODIC.has(id)){requireCaps('status','damage');const prior=impl.onStage;impl.onStage=(ctx,e)=>{prior?.(ctx,e);if(e.kind!=='status-periodic')return;validatePeriodic(e,scope);if(e.status?.values?.abilityId!==id||e.status.abilityId!==undefined&&e.status.abilityId!==id)return;if(e.status.target!==e.actor)throw Error('B periodic target mismatch');const interval=number(e.intervalSeconds,'status interval');if(interval<=0||typeof e.enabled!=='boolean')throw Error('Invalid B periodic clock facts');if(e.enabled&&ctx.actor(e.actor).alive&&e.status.values.dps)damage(ctx,id,e.status.owner,e.actor,number(e.status.values.dps,'status dps')*interval,'magical',e.status.values.reflected===true);};}
 impl.requires=[...new Set(impl.requires)];
 impl.onDeath=(ctx,e)=>{const s=readOwner(ctx,e.actor);if(impl.requires.includes('schedule'))for(const h of s.jobs)ctx.cancelJob(h);if(impl.requires.includes('legacy-effect'))for(const h of s.areas)ctx.legacyEffect.end(h,'owner-dead');if(impl.requires.includes('status'))for(const key of id==='huskar_burning_spear'?Array.from({length:32},(_,i)=>id+'_'+i):id==='treant_overgrowth'?[id,id+'_control']:[id])removeKey(ctx,e.actor,key);writeOwner(ctx,e.actor,{toggle:false,sequence:s.sequence,jobs:[],areas:[]});};
 if(AREAS.has(id)){const prior=impl.onContact;impl.onContact=(ctx,e)=>{if(e.kind==='effect-end'){forget(ctx,e.actor,'areas',e.handle);return;}return prior?.(ctx,e);};}
 return impl;
}
