import {codeIdentity,defineStateSchema} from '../../index.js';
const handles={type:'array',maxItems:64,items:{type:'string',minLength:1,maxLength:256}};
const owner={type:'object',properties:{toggle:{type:'boolean'},sequence:{type:'integer',minimum:0,maximum:31},jobs:handles,areas:handles},required:['toggle','sequence','jobs','areas'],additionalProperties:false};
export function createBStateSchema(){return defineStateSchema({id:'heros/b-scoped-state',version:'2.0.0',schema:{anyOf:[{type:'null'},{type:'object',properties:{version:{const:1},owners:{type:'object',properties:{'0':owner,'1':owner},required:[],additionalProperties:false}},required:['version','owners'],additionalProperties:false}]},refinement:{id:'b/scoped-handle-uniqueness',...codeIdentity(['rules/b/state.js']),validate:validateBState}});}
const statusSupportSchema={type:'object',properties:{version:{const:'b-status-record-view-1'},mode:{enum:['legacy','strict']},record:{const:'StatusRecordView'},periodic:{const:'status-periodic'},refresh:{const:'statusRefresh'},block:{const:'statusBlockUpdate'},readonlyCrossKeys:{type:'array',maxItems:1,items:{enum:['night_stalker_darkness']}},handles:{const:'provider-authenticated-origin'}},required:['version','mode','record','periodic','refresh','block','readonlyCrossKeys','handles'],additionalProperties:false};
export function statusContractFor(id,mode='legacy'){return {version:'b-status-record-view-1',mode,record:'StatusRecordView',periodic:'status-periodic',refresh:'statusRefresh',block:'statusBlockUpdate',readonlyCrossKeys:['night_stalker_void','night_stalker_crippling_fear'].includes(id)?['night_stalker_darkness']:[],handles:'provider-authenticated-origin'};}
export const B_EXECUTION_SCHEMA=defineStateSchema({id:'heros/b-execution-parameters',version:'2.1.0',schema:{type:'object',properties:{damageScale:{type:'number',minimum:0,maximum:1},healScale:{type:'number',minimum:0,maximum:1},statusContract:statusSupportSchema},required:['damageScale','healScale'],additionalProperties:false}});
export function executionParameters(config){if(!B_EXECUTION_SCHEMA.validate(config.parameters))throw Error('Invalid B execution parameters');const statusContract=config.parameters.statusContract??statusContractFor(config.definition.id);if(statusContract.readonlyCrossKeys.join(',')!==statusContractFor(config.definition.id).readonlyCrossKeys.join(','))throw Error('Invalid B readonly cross-key declaration');return {...config.parameters,statusContract};}
// Only own flags/sequence and scoped handles. No actors/resources/clock/world arrays.
export function validateBState(s){if(s===null)return true;if(!s||Array.isArray(s)||Object.keys(s).sort().join(',')!=='owners,version'||s.version!==1||!s.owners||Array.isArray(s.owners)||Object.keys(s.owners).some(k=>k!=='0'&&k!=='1'))return false;return Object.values(s.owners).every(v=>v&&Object.keys(v).sort().join(',')==='areas,jobs,sequence,toggle'&&typeof v.toggle==='boolean'&&Number.isInteger(v.sequence)&&v.sequence>=0&&v.sequence<32&&['jobs','areas'].every(k=>Array.isArray(v[k])&&v[k].length<=64&&v[k].every(h=>typeof h==='string'&&h.length>0&&h.length<=256)&&new Set(v[k]).size===v[k].length));}
export function readOwner(ctx,actor){return ctx.state.read()?.owners?.[actor]??{toggle:false,sequence:0,jobs:[],areas:[]};}
export function writeOwner(ctx,actor,value){const s=ctx.state.read()??{version:1,owners:{}};ctx.state.write({...s,owners:{...s.owners,[actor]:value}});}
export function toggle(ctx,actor){const s=readOwner(ctx,actor);writeOwner(ctx,actor,{...s,toggle:!s.toggle});}
export function remember(ctx,actor,kind,handle){if(typeof handle!=='string')throw Error('Missing bounded effect handle');const s=readOwner(ctx,actor);if(s[kind].length>=64)throw Error('B scoped handle capacity');writeOwner(ctx,actor,{...s,[kind]:[...s[kind],handle]});}
export function forget(ctx,actor,kind,handle){const s=readOwner(ctx,actor);writeOwner(ctx,actor,{...s,[kind]:s[kind].filter(h=>h!==handle)});}
