import {event,num,flag,handle,actor,direction,near,hit,program,status,cue,log} from './remaining-common.js';
const AREA=['juggernaut_blade_fury','juggernaut_healing_ward','pudge_rot','sniper_shrapnel'];
const DOT=['crystal_maiden_frostbite','axe_hunger'];
export function buildEffect(config){const id=config.definition.id,m=config.definition.mvp;
 if(AREA.includes(id)){const features=['legacy-hit-v1','legacy-field-v1','legacy-status-v1'];const ward=id==='juggernaut_healing_ward',fury=id==='juggernaut_blade_fury',rot=id==='pudge_rot';
 return {features,requires:[],activate(ctx,e){event(config,e,features,['aimX','toggleActive']);num(e.aimX,'aimX',-10000,10000);flag(e.toggleActive,'toggleActive');const f=ctx.actor(e.owner),commands=[];
  if(rot&&e.toggleActive)return program(config,[{kind:'status.remove',target:e.owner,key:'aura',handle:null},{kind:'effect.end',owner:e.owner,handle:null,scope:'owner-ability',reason:'toggle'}]);
  if(fury&&m.debuffImmune)commands.push({kind:'cleanse',target:e.owner,tier:'basic'});
  if(fury||rot)commands.push(status(e.owner,'aura',m.duration_s,{magicReduction:m.magic_reduction||0,debuffImmune:!!m.debuffImmune,endDispel:m.endDispel||'none',blocksBasicAttack:fury}));
  const profile=ward?'ward':rot||fury?'aura':'ground_dot';
  commands.push({kind:'effect.spawn',owner:e.owner,profile,x:profile==='ground_dot'?e.aimX:f.x,duration:m.duration_s,interval:m.tick_interval_s,radius:m.radius_wu,followSpeed:ward?(m.officialSemantic.ward_move_speed||325)*.55:0,replace:ward?'silent-owner-ward':'none',terminal:fury||rot?'marker-required':'include',ownerDeath:ward||fury||rot?'end':'preserve'});
  if(ward)commands.push(log(e.owner,'ward_spawn',{x:f.x,duration:m.duration_s,radius:m.radius_wu}),cue('ward_spawn',e.owner,e.owner,f.x,190));return program(config,commands);},
 onStage(ctx,e){event(config,e,features,['effectHandle','phase','x','remainingLife','liveDt','due','markerActive','reason','healed','healTicks']);handle(e.effectHandle);num(e.x,'x',-10000,10000);num(e.remainingLife,'remainingLife',-1,1000);num(e.liveDt,'liveDt',0,.05);flag(e.due,'due');flag(e.markerActive,'markerActive');num(e.healed,'healed');num(e.healTicks,'healTicks',0,1e7);const f=ctx.actor(e.owner),t=ctx.actor(e.target),commands=[];
  if(e.phase==='buff-expiring'){if(!fury||e.reason!=='expired')throw Error('Unexpected marker expiry');if(m.endDispel)commands.push({kind:'cleanse',target:e.owner,tier:m.endDispel});return program(config,commands);}
  if(e.phase==='effect-end'){if(!['expired','owner-dead','cancelled','attack','replace'].includes(e.reason))throw Error('Invalid effect reason');if(ward&&e.reason!=='replace')commands.push(log(e.owner,'ward_end',{reason:e.reason==='owner-dead'?'owner_defeated':e.reason,attacker:e.reason==='attack'?e.target:null,healed:e.healed,ticks:e.healTicks}));if(ward&&e.reason==='attack')commands.push(cue('ward-destroy',e.owner,e.target,e.x,50));return program(config,commands);}
  if(e.phase!=='zone-tick'||e.reason!=='none')throw Error('Wrong zone stage');if((ward||fury||rot)&&!f.alive)return program(config,[{kind:'effect.end',owner:e.owner,handle:e.effectHandle,scope:'handle',reason:'owner-dead'}]);if((fury||rot)&&!e.markerActive)return program(config,[{kind:'effect.end',owner:e.owner,handle:e.effectHandle,scope:'handle',reason:'marker-removed'}]);if(!e.due)return program(config,[]);
  if(ward){if(Math.abs(f.x-e.x)<=m.radius_wu)commands.push({kind:'heal',target:e.owner,amount:f.maxHp*(m.officialSemantic.heal_max_hp_pct_per_s||0)/100*m.tick_interval_s,receipt:e.effectHandle});}
  else {if(Math.abs(t.x-e.x)<=m.radius_wu+22&&(id!=='sniper_shrapnel'||t.y<45))commands.push(hit(config,e.owner,e.target,{dot:true,suppressFiery:true,slowSeconds:m.slow_linger_s??Math.min(m.slow_duration_s??1,m.tick_interval_s||.2),projection:fury?'juggernaut_blade_dance':null}));if(m.self_damage_per_tick)commands.push({kind:'self.damage',target:e.owner,amount:m.self_damage_per_tick,nonlethal:true});}return program(config,commands);
 }};
 }
 if(DOT.includes(id)){const features=['legacy-hit-v1','legacy-dot-v1','legacy-status-v1'];return {features,requires:['target-route'],activate(ctx,e){event(config,e,features,['reflected']);flag(e.reflected,'reflected');const routed=ctx.target.route({owner:e.owner,target:e.target,abilityId:id,range:m.range_wu,reflectable:true,reflected:e.reflected});if(!routed||typeof routed.accepted!=='boolean'||typeof routed.reflected!=='boolean'||routed.originalOwner!==e.owner)throw Error('Missing finite targeted route');actor(routed.owner);actor(routed.target);if(!routed.accepted)return program(config,[]);const reflected=routed.reflected,t=ctx.actor(routed.target);
  if(!reflected&&(!near(ctx,e,m.range_wu)||t.guarding||t.invulnerable))return program(config,[]);
  const commands=[{kind:'dot.apply',source:routed.owner,target:routed.target,duration:m.duration_s,interval:m.tick_interval_s,replace:!reflected,rootPolicy:id==='crystal_maiden_frostbite'?(reflected?'unconditional-direct':'nonimmune-direct'):'none',rootSeconds:id==='crystal_maiden_frostbite'?m.duration_s:0,dispel:m.dispelTier}];if(reflected)commands.push(cue('reflect',routed.owner,routed.target));else if(id==='crystal_maiden_frostbite'&&!t.debuffImmune)commands.push(cue('root',routed.owner,routed.target,t.x,t.y+50,0));return program(config,commands);},
 onStage(ctx,e){event(config,e,features,['source','dotHandle','phase','remainingLife','elapsed','due','reflected']);actor(e.source);handle(e.dotHandle);if(e.target!==1-e.source||e.phase!=='fighter-dot')throw Error('Wrong DOT stage');num(e.remainingLife,'remainingLife',-.05,1000);num(e.elapsed,'elapsed',0,1001);flag(e.due,'due');flag(e.reflected,'reflected');return program(config,e.due?[hit(config,e.source,e.target,{dot:true,suppressFiery:true,stun:0,hitstun:0,slowSeconds:Math.min(m.slow_duration_s??1,Math.max(0,e.remainingLife))})]:[]);}};}
 if(id==='crystal_maiden_nova'){const features=['legacy-hit-v1'];return {features,requires:[],activate(ctx,e){event(config,e,features,['aimX']);num(e.aimX,'aimX',-10000,10000);const t=ctx.actor(e.target),commands=[];if(Math.abs(t.x-e.aimX)<=m.radius_wu+22&&t.y<45)commands.push(hit(config,e.owner,e.target));commands.push(cue('pillar',e.owner,e.target,e.aimX,0,m.radius_wu));return program(config,commands);}};}
 if(id==='juggernaut_omnislash'){const features=['legacy-hit-v1','legacy-job-v1','legacy-status-v1','legacy-contact-v1'];return {features,requires:[],activate(ctx,e){event(config,e,features,[]);if(m.invulnerable_active&&!near(ctx,e,m.range_wu))return program(config,[]);const commands=m.invulnerable_active?[{kind:'cleanse',target:e.owner,tier:'basic'},{kind:'protect',target:e.owner,seconds:m.duration_s}]:[];for(let n=0;n<m.ticks;n++)commands.push({kind:'job.spawn',owner:e.owner,target:e.target,index:n,offset:m.tick_offsets_s?.[n]??n*m.tick_interval_s,profile:'omnislash'});return program(config,commands);},onStage(ctx,e){event(config,e,features,['phase','jobHandle','index','blocked']);handle(e.jobHandle);if(e.phase!=='due-skill-hit'||!Number.isInteger(e.index)||e.index<0||e.index>=m.ticks)throw Error('Wrong scheduled hit');flag(e.blocked,'blocked');const f=ctx.actor(e.owner),t=ctx.actor(e.target);if(!f.alive||e.blocked||!near(ctx,e,m.tracking_break_wu||m.range_wu||m.radius_wu))return program(config,[]);return program(config,[{kind:'motion',target:e.owner,x:t.x-f.dir*75},cue('slash',e.owner,e.target,t.x,t.y+100,160,f.dir),hit(config,e.owner,e.target,{amount:m.hit_damages?.[e.index]??m.damage,basic:true,projection:'juggernaut_blade_dance'})]);}};}
 return null;
}
