export const EVENT_VERSION='heros-host-events-1';
export const FEATURE_NAMES=Object.freeze(['legacy-hit-v1','legacy-linear-v1','legacy-dot-v1','legacy-field-v1','legacy-motion-v1','legacy-job-v1','legacy-channel-v1','legacy-souls-v1','legacy-property-v1','legacy-ward-cleave-v1','legacy-shell-v1','legacy-status-v1','legacy-passive-v1']);
export const num=(v,k,min=0,max=1e7)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw Error('Invalid legacy fact/coefficient: '+k);return v;};
export const flag=(v,k)=>{if(typeof v!=='boolean')throw Error('Missing legacy boolean: '+k);return v;};
export const actor=v=>{if(v!==0&&v!==1)throw Error('Invalid legacy actor');return v;};
export const handle=v=>{if(typeof v!=='string'||!v||v.length>128)throw Error('Missing bounded legacy handle');return v;};
export function capabilities(values){if(!Array.isArray(values)||values.length>FEATURE_NAMES.length||new Set(values).size!==values.length||values.some(x=>!FEATURE_NAMES.includes(x)))throw Error('Unknown legacy proposed capabilities');return [...values].sort();}
export function admitted(config,event,features){return config.parameters.hostSemantics===EVENT_VERSION&&event.legacySemantics===EVENT_VERSION&&Array.isArray(event.legacyCapabilities)&&features.every(f=>config.parameters.hostCapabilities.includes(f)&&event.legacyCapabilities.includes(f));}
export function gate(config,event,features){if(!admitted(config,event,features))throw Error('GATED: missing native legacy capabilities '+features.join(','));capabilities(event.legacyCapabilities);if(event.slot!==undefined&&event.slot!==config.parameters.slot)throw Error('Wrong originating rule slot');actor(event.owner);actor(event.target);}
export function near(ctx,e,r,ground=false){const f=ctx.actor(e.owner),t=ctx.actor(e.target);return Math.abs(t.x-f.x)<=r+22&&(!ground||t.y<45);}
export function hit(definition,source,target,amount=definition.mvp.damage,extra={}){const m=definition.mvp;return {source:actor(source),target:actor(target),abilityId:definition.id,amount:num(amount,'damage'),type:m.damage_type,blockable:m.blockable,stunSeconds:m.stun_s,hitstunSeconds:m.hitstun_s,...extra};}
export function hitEffects(m){return {profile:'legacy-hit-v1',...(m.slow_pct?{slow:{percent:m.slow_pct,seconds:m.slow_duration_s??1}}:{}),...(m.control?{controlKind:m.control}:{}),...(m.knockback_wu?{knockbackDistance:m.knockback_wu}:{}),...(m.pull_to_distance?{pullDistance:m.pull_to_distance,pullStunSeconds:m.pull_cap_s||.25}:{}),...(m.selfReflection?{selfReflectionFraction:m.selfReflection}:{}),...(m.vulnerability_physical?{vulnerabilityPhysical:{fraction:m.vulnerability_physical,seconds:m.vulnerability_s,dispel:'basic'}}:{})};}
export function ring(owner,radius,x=null,y=60,lifeSeconds=.65){return {kind:x===null?'legacy-ring':'legacy-effect-ring',actor:owner,...(x===null?{}:{x}),y,radius,lifeSeconds};}
export function status(definition,owner,target,key,duration,values,negative=false,dispel='none'){return {owner,target,abilityId:definition.id,key,duration,polarity:negative?'negative':'positive',dispel,pierces:negative,values:{profile:'legacy-v8',...values}};}
export function ownView(ctx,e,definition,key){const rows=ctx.status.query(actor(e.actor??e.owner),key);if(!Array.isArray(rows)||rows.length>1)throw Error('Invalid unique legacy status view');return rows.filter(r=>{if(r.owner!==e.owner||r.abilityId!==definition.id)return false;handle(r.handle);num(r.remainingSeconds,'remainingSeconds',0,3600);flag(r.effective,'effective');if(r.values?.profile!=='legacy-v8')throw Error('Wrong legacy source profile');return r.remainingSeconds>1e-8&&r.effective;});}
export function dot(definition,owner,target,duration,interval,data,dispel='none'){return status(definition,owner,target,definition.id,duration,{kind:'legacy-dot',intervalSeconds:interval,pulseHandler:'legacy-dot-pulse',originalCancellation:'target-fighter-stage; retain-dead-source',...data},true,dispel);}
export function validateCoefficients(m){function visit(v,key='mvp'){if(typeof v==='number')num(v,key,-1e7,1e7);else if(v&&typeof v==='object')for(const [k,x]of Object.entries(v))visit(x,k);}visit(m);for(const [k,v]of Object.entries(m))if(typeof v==='number')num(v,k);for(const k of ['duration_s','slow_duration_s','vulnerability_s','stack_duration_s','debuff_duration_s','travelDuration','tick_interval_s'])if(m[k]!==undefined)num(m[k],k,0,3600);for(const k of ['selfReflection','vulnerability_physical','self_slow','block_fraction_cap','lost_hp_multiplier'])if(m[k]!==undefined)num(m[k],k,0,1);if(!['physical','magical','pure','none'].includes(m.damage_type))throw Error('Invalid legacy damage enum');if(m.stun_s!==undefined)num(m.stun_s,'stun_s',0,60);if(m.hitstun_s!==undefined)num(m.hitstun_s,'hitstun_s',0,60);if(m.slow_pct!==undefined)num(m.slow_pct,'slow_pct',0,100);if(m.control!==undefined&&!['fear','stun','root','hex','taunt'].includes(m.control))throw Error('Unknown legacy control kind');for(const k of ['damage','radius_wu','range_wu','duration_s','mana','cooldown_s','startup_frames','recovery_frames'])if(m[k]!==undefined)num(m[k],k);}
