import {gate,num,flag,actor,handle,near,hit,hitEffects,ring,status,dot,ownView} from './remaining-common.js';
export function buildEffect(config){const {definition}=config,id=definition.id,m=definition.mvp;
 const build=(features,requires,hooks)=>({features,requires,...hooks});
 const requireOverload=e=>{if(e.overloadCommitted!==true)throw Error('GATED: owned Overload commit callback missing');};
 if(id==='earthshaker_fissure')return build(['legacy-hit-v1','legacy-field-v1','legacy-passive-v1'],['damage','legacy-effect'],{activate(ctx,e){gate(config,e,['legacy-hit-v1','legacy-field-v1','legacy-passive-v1']);if(e.aftershockCompleted!==true)throw Error('GATED: owned Aftershock incomplete');const x=num(e.aimX,'aimX',45,1155);const h=ctx.legacyEffect.spawn({owner:e.owner,abilityId:id,castId:handle(e.castId),kind:'wall',x,radius:m.radius_wu,duration:m.duration_s,data:{profile:'legacy-fissure-wall',height:m.wall_height_wu||55,width:m.wall_width_wu,movementHalfWidth:35,sourceDeathPolicy:'retain',initialHitOnly:true}});const t=ctx.actor(e.target);if(Math.abs(t.x-x)<=m.radius_wu+22&&t.y<45)ctx.damage(hit(definition,e.owner,e.target));return {effectHandle:h};}});
 if(id==='mirana_starstorm'){
  const features=['legacy-hit-v1','legacy-job-v1'];if(!Number.isInteger(m.ticks)||m.ticks<1||m.ticks>64||m.hit_damages.length!==m.ticks||m.tick_offsets_s.length!==m.ticks)throw Error('Invalid bounded Starstorm program');m.hit_damages.forEach(v=>num(v,'Starstorm hit'));m.tick_offsets_s.forEach(v=>num(v,'Starstorm offset',0,3600));
  const deliver=(ctx,e)=>{gate(config,e,features);if(e.kind!=='legacy-starstorm-due')throw Error('Wrong Starstorm stage');handle(e.handle);const f=ctx.actor(e.owner);flag(e.blocked,'blocked');if(f.alive&&!e.blocked&&near(ctx,e,num(e.range,'range')))return ctx.damage(hit(definition,e.owner,e.target,num(e.capturedAmount,'capturedAmount'),{legacyInfo:{linaDone:true}}));return {skipped:true};};
  return build(features,['schedule','damage'],{activate(ctx,e){gate(config,e,features);const jobs=[];for(let n=0;n<m.ticks;n++)jobs.push(ctx.schedule({abilityId:id,owner:e.owner,target:e.target,handler:'legacy-starstorm-hit',delay:num(m.tick_offsets_s[n],'offset'),data:{kind:'legacy-starstorm-due',profile:'legacy-event-stage',capturedAmount:m.hit_damages[n],range:m.tracking_break_wu||m.range_wu||m.radius_wu,owner:e.owner,target:e.target,legacySemantics:e.legacySemantics,legacyCapabilities:e.legacyCapabilities,cancellation:'check-alive-blocked-at-delivery; retain-until-due'}}));return {jobs};},scheduledHandlers:{'legacy-starstorm-hit':deliver}});
 }
 if(id==='mirana_leap'||id==='zeus_jump'){
  const features=['legacy-motion-v1','legacy-status-v1',...(id==='zeus_jump'?['legacy-hit-v1']:[])];num(m.range_wu,'range_wu',0,8845);num(m.travelDuration||.55,'travelDuration',Number.MIN_VALUE,3600);num(m.range_wu/(m.travelDuration||.55),'leap speed');
  return build(features,['motion-request','status',...(id==='zeus_jump'?['damage']:[])],{activate(ctx,e){gate(config,e,features);if(id==='zeus_jump'&&near(ctx,e,m.radius_wu,m.height==='ground'))ctx.damage(hit(definition,e.owner,e.target,m.damage,{legacyEffects:hitEffects(m)}));const f=ctx.actor(e.owner);const h=ctx.motion({actor:e.owner,abilityId:id,castId:handle(e.castId),kind:'leap',destinationX:f.x+e.direction*m.range_wu,speed:m.range_wu/(m.travelDuration||.55),duration:m.travelDuration||.55,profile:'legacy-leap',verticalLaunch:650,direction:e.direction});ctx.status.apply(status(definition,e.owner,e.owner,'leapSpeed',m.duration_s||2,{kind:'legacy-buff',coefficients:{move_multiplier:m.move_multiplier||1.1,attack_interval_multiplier:m.attack_interval_multiplier||1},nativeAdmission:'self-even-invulnerable'}));return {motionHandle:h};}});
 }
 if(id==='shadow_fiend_raze'){
  const features=['legacy-hit-v1','legacy-status-v1','legacy-souls-v1'];num(m.stack_damage,'stack_damage');num(m.max_stacks,'max_stacks',0,1024);num(m.stack_duration_s,'stack_duration_s',0,3600);num(m.damage+40+m.stack_damage*1024,'derived Raze');
  return build(features,['status','damage'],{activate(ctx,e){gate(config,e,features);const souls=num(e.nativeSouls,'nativeSouls',0,20),x=num(e.aimX,'aimX',45,1155),t=ctx.actor(e.target);if(Math.abs(t.x-x)<=m.radius_wu+22&&(m.height!=='ground'||t.y<45)){const rows=ctx.status.query(e.target,'raze');if(rows.length>1)throw Error('Duplicate native Raze key');let stacks=0;if(rows.length){handle(rows[0].handle);stacks=num(rows[0].values?.stacks,'raze stacks',0,1024);}ctx.status.apply(status(definition,e.owner,e.target,'raze',m.stack_duration_s||2,{kind:'raze-stack',stacks:Math.min(m.max_stacks,stacks+1),nativeAdmission:'geometry-before-hit-even-invulnerable-or-dead'},true));ctx.damage(hit(definition,e.owner,e.target,m.damage+souls*2+stacks*m.stack_damage));}return {presentation:{kind:'ground-pillar',aimX:x,radius:m.radius_wu,lifeSeconds:.6}};}});
 }
 if(id==='shadow_fiend_feast'){
  const features=['legacy-status-v1','legacy-souls-v1','legacy-property-v1'];num(m.souls,'souls',0,20);const interval=m.officialSemantic?.collection_interval_s||.5;num(interval,'collection interval',Number.MIN_VALUE,3600);
  return build(features,['status'],{activate(ctx,e){gate(config,e,features);ctx.status.apply(status(definition,e.owner,e.owner,id,m.duration_s||2,{kind:'feast',coefficients:{attack_interval_multiplier:m.attack_interval_multiplier,move_multiplier:m.move_multiplier},collectedSouls:0,intervalSeconds:interval,pulseHandler:'legacy-feast-collect',expiryHandler:'legacy-feast-expire'}));return {presentation:{kind:'legacy-buff-ring',actor:e.owner,yOffset:70,radius:100,lifeSeconds:.7}};},onStage(ctx,e){gate(config,e,features);if(e.kind==='legacy-movement-properties'){const rows=ownView(ctx,e,definition,id);return {nativeProperties:rows.length?rows[0].values.coefficients:{}};}const souls=num(e.nativeSouls,'nativeSouls',0,20),collected=num(e.collectedSouls,'collectedSouls',0,20),h=handle(e.handle);if(e.kind==='legacy-feast-expire')return {legacySoulUpdate:{actor:e.owner,sourceStatusHandle:h,operation:'feast-expiry',value:Math.max(0,souls-collected)}};if(e.kind!=='legacy-feast-collect')throw Error('Wrong Feast stage');const remaining=num(e.remainingSeconds,'remainingSeconds',-1,3600);if(remaining<=1e-7||collected||!ctx.actor(e.target).alive||!near(ctx,e,m.radius_wu))return {skipped:true};const amount=Math.min(m.souls,20-souls);return {legacySoulUpdate:{actor:e.owner,sourceStatusHandle:h,operation:'feast-collect',value:souls+amount,collectedSouls:amount},log:{kind:'souls',actor:e.owner,amount,target:e.target}};},projectAttack(ctx,e){gate(config,e,features);if(e.stage!=='legacy-base-attack-souls')throw Error('Wrong soul attack stage');return {addAfterAttackBonus:num(e.nativeSouls,'nativeSouls',0,20)};},projectInterval(ctx,e){gate(config,e,features);const rows=ownView(ctx,e,definition,id);return {nativeProperties:rows.length?rows[0].values.coefficients:{}};}});
 }
 if(id==='shadow_fiend_requiem'){const features=['legacy-hit-v1','legacy-souls-v1'];num(m.damage*3,'derived Requiem');return build(features,['damage'],{activate(ctx,e){gate(config,e,features);const souls=num(e.nativeSouls,'nativeSouls',0,20);if(near(ctx,e,m.radius_wu,m.height==='ground'))ctx.damage(hit(definition,e.owner,e.target,m.damage*Math.max(1,Math.min(3,souls)),{legacyEffects:hitEffects(m)}));return {presentation:ring(e.owner,m.radius_wu)};}});}
 if(id==='storm_spirit_remnant'){
  const features=['legacy-hit-v1','legacy-field-v1','legacy-passive-v1'];num(m.walkSpeed,'walkSpeed');num(m.arming_s,'arming_s');num(m.triggerRadius,'triggerRadius');
  return build(features,['legacy-effect','damage'],{activate(ctx,e){gate(config,e,features);requireOverload(e);return {effectHandle:ctx.legacyEffect.spawn({owner:e.owner,abilityId:id,castId:handle(e.castId),kind:'trap',x:ctx.actor(e.owner).x,radius:m.radius_wu,duration:m.duration_s,data:{profile:'legacy-walking-remnant',targetX:num(e.aimX,'aimX',45,1155),walkSpeed:m.walkSpeed,armingSeconds:m.arming_s,triggerRadius:m.triggerRadius,contactHandler:'legacy-remnant-contact',sourceDeathPolicy:'retain',walkUsesWholeDt:true}})};},onContact(ctx,e){gate(config,e,features);if(e.kind!=='legacy-remnant-contact')throw Error('Wrong Remnant contact');handle(e.handle);const x=num(e.effectX,'effectX',0,1200),age=num(e.ageSeconds,'ageSeconds'),t=ctx.actor(e.target);if(age<m.arming_s||t.y>=45||Math.abs(t.x-x)>(m.triggerRadius??m.radius_wu)+22)return {skipped:true};if(Math.abs(t.x-x)<=m.radius_wu+22)ctx.damage(hit(definition,e.owner,e.target));ctx.legacyEffect.end(e.handle,'contact');return {presentation:ring(e.owner,m.radius_wu,x,50,.5)};}});
 }
 if(id==='storm_spirit_vortex'){
  const features=['legacy-hit-v1','legacy-motion-v1','legacy-passive-v1'];return build(features,['target-route','damage','cue'],{activate(ctx,e){gate(config,e,features);requireOverload(e);if(!near(ctx,e,m.range_wu,m.height==='ground'))return;const r=ctx.target.route({owner:e.owner,target:e.target,abilityId:id,range:m.range_wu,reflectable:true,reflected:e.reflected});if(!r.accepted)return;ctx.damage(hit(definition,r.owner,r.target,m.damage,{reflected:r.reflected,legacyEffects:hitEffects(m)}));if(r.reflected){ctx.cue({kind:'reflect',abilityId:id,actor:r.owner,target:r.target});return {reflected:true};}}});
 }
 if(id==='storm_spirit_ball'){
  const features=['legacy-hit-v1','legacy-motion-v1','legacy-passive-v1'];num(m.duration_s,'duration_s',Number.MIN_VALUE,3600);num(m.range_wu,'range_wu',Number.MIN_VALUE,8845);num(m.range_wu/m.duration_s,'ball speed');
  return build(features,['motion-request','protect','damage'],{activate(ctx,e){gate(config,e,features);requireOverload(e);const h=ctx.motion({actor:e.owner,abilityId:id,castId:handle(e.castId),kind:'dash',destinationX:ctx.actor(e.owner).x+e.direction*m.range_wu,speed:m.range_wu/m.duration_s,duration:m.duration_s,profile:'legacy-ball-contact',direction:e.direction,maxDistance:m.range_wu,contactHandler:'legacy-ball-contact',oneHit:true,trackActualMovement:true});ctx.protect({actor:e.owner,abilityId:id,kind:'invulnerability',duration:m.duration_s});return {motionHandle:h};},onContact(ctx,e){gate(config,e,features);if(e.kind!=='legacy-ball-contact')throw Error('Wrong Ball contact');handle(e.handle);const distance=num(e.actualDistance,'actualDistance');if(!m.damage)return {motionContactIgnored:true};ctx.damage(hit(definition,e.owner,e.target,m.damage*Math.min(1,distance/m.range_wu)));return {motionMarkHit:{handle:e.handle}};}});
 }
 if(id==='queen_of_pain_scream'){const features=['legacy-hit-v1'];num(m.selfReflection,'selfReflection',0,1);return build(features,['damage'],{activate(ctx,e){gate(config,e,features);if(near(ctx,e,m.radius_wu,m.height==='ground'))ctx.damage(hit(definition,e.owner,e.target,m.damage,{legacyEffects:hitEffects(m)}));return {presentation:ring(e.owner,m.radius_wu)};}});}
 if(id==='witch_doctor_restoration'){
  const features=['legacy-field-v1','legacy-status-v1','legacy-hit-v1'];num(m.mana_per_second,'mana_per_second');num(m.ticks,'ticks',Number.MIN_VALUE);num(m.heal_total/m.ticks,'heal per tick');num(m.tick_interval_s,'tick_interval_s',Number.MIN_VALUE,3600);
  return build(features,['legacy-effect','status','mana','heal'],{activate(ctx,e){gate(config,e,features);if(flag(e.toggleActive,'toggleActive')){for(const r of ownView(ctx,e,definition,id))ctx.status.remove(r.handle);return {legacyRestorationToggleOff:{owner:e.owner,abilityId:id,endAllOwnAreas:true,commitAction:true}};}ctx.status.apply(status(definition,e.owner,e.owner,id,m.duration_s||2,{kind:'restoration-marker',interruptOnCC:true}));return {effectHandle:ctx.legacyEffect.spawn({owner:e.owner,abilityId:id,castId:handle(e.castId),kind:'area',x:ctx.actor(e.owner).x,radius:m.radius_wu,duration:m.duration_s,data:{profile:'legacy-restoration',intervalSeconds:m.tick_interval_s,initialTick:m.tick_interval_s,stageHandler:'legacy-restoration-advance',markerKey:id,markerPolicy:'same-key-not-generation-bound',manaDrainUsesWholeDt:true,sourceDeathPolicy:'end-area-retain-native-buff'}})};},onStage(ctx,e){gate(config,e,features);if(e.kind!=='legacy-restoration-advance')throw Error('Wrong restoration zone stage');handle(e.handle);const dt=num(e.wholeDt,'wholeDt',0,1),pulse=flag(e.pulseDue,'pulseDue'),present=flag(e.markerPresent,'markerPresent');if(!ctx.actor(e.owner).alive){ctx.legacyEffect.end(e.handle,'owner-dead');return {stopped:true};}ctx.mana({actor:e.owner,abilityId:id,delta:-m.mana_per_second*dt});if(ctx.actor(e.owner).mp<=0){for(const r of ownView(ctx,e,definition,id))ctx.status.remove(r.handle);ctx.legacyEffect.end(e.handle,'cancelled');return {stopped:true,reason:'mana-zero',noPulse:true};}if(!present){ctx.legacyEffect.end(e.handle,'cancelled');return {stopped:true,reason:'marker-absent',noPulse:true};}if(pulse)return {receipt:ctx.heal({source:e.owner,target:e.owner,abilityId:id,amount:m.heal_total/m.ticks,legacySource:'heal'})};return {pulse:false};}});
 }
 if(id==='witch_doctor_maledict'){
  const features=['legacy-hit-v1','legacy-dot-v1'];num(m.tick_interval_s,'tick_interval_s',Number.MIN_VALUE,3600);num(m.lost_hp_multiplier,'lost_hp_multiplier');num(m.burstInterval,'burstInterval',Number.MIN_VALUE,3600);
  return build(features,['status','damage'],{activate(ctx,e){gate(config,e,features);const t=ctx.actor(e.target);if(Math.abs(t.x-num(e.aimX,'aimX',45,1155))<=m.radius_wu+22&&!t.guarding&&!t.invulnerable)ctx.status.apply(dot(definition,e.owner,e.target,m.duration_s,m.tick_interval_s,{baselineHp:t.hp,elapsed:0,nextBurst:m.burstInterval,burstInterval:m.burstInterval,burstHandler:'legacy-maledict-burst',replaceSameId:true,admission:'no-guard-no-invuln; ignore-immunity'},'none'));},onStage(ctx,e){gate(config,e,features);handle(e.handle);if(e.kind==='legacy-dot-pulse')return ctx.damage(hit(definition,actor(e.effectiveOwner??e.owner),e.target,m.damage,{dot:true,stunSeconds:0,hitstunSeconds:0,legacyInfo:{linaDone:true}}));if(e.kind!=='legacy-maledict-burst')throw Error('Wrong Maledict stage');const baseline=num(e.baselineHp,'baselineHp');return ctx.damage(hit(definition,actor(e.effectiveOwner??e.owner),e.target,num(Math.max(0,baseline-ctx.actor(e.target).hp)*m.lost_hp_multiplier,'maledict burst'),{dot:true,legacyInfo:{linaDone:false}}));}});
 }
 if(id==='witch_doctor_death_ward'){
  const features=['legacy-channel-v1','legacy-field-v1','legacy-hit-v1'];num(m.tick_interval_s,'tick_interval_s',Number.MIN_VALUE,3600);
  return build(features,['legacy-effect','damage'],{activate(ctx,e){gate(config,e,features);return {effectHandle:ctx.legacyEffect.spawn({owner:e.owner,abilityId:id,castId:handle(e.castId),kind:'death-ward',x:num(e.aimX,'aimX',45,1155),radius:m.radius_wu,duration:m.duration_s,data:{profile:'legacy-death-ward',invulnerable:true,intervalSeconds:m.tick_interval_s,pulseHandler:'legacy-death-ward-pulse',channel:{slot:e.slot,castId:e.castId,duration:m.duration_s+1/60,cancelProfile:'legacy-held; move-control-silence-release',recoveryActive:0,recoveryCancelled:.2,recoveryExpired:.25}}})};},onStage(ctx,e){gate(config,e,features);if(e.kind!=='legacy-death-ward-pulse')throw Error('Wrong death-ward stage');handle(e.handle);if(!ctx.actor(e.owner).alive||!flag(e.channelValid,'channelValid')){ctx.legacyEffect.end(e.handle,'cancelled');return {stopped:true};}const x=num(e.effectX,'effectX',0,1200),t=ctx.actor(e.target);if(Math.abs(t.x-x)<=m.radius_wu+22){ctx.damage(hit(definition,e.owner,e.target,m.damage,{legacyInfo:{linaDone:true}}));return {presentation:{kind:'legacy-ward-beam',actor:e.owner,target:e.target,x,y:80,targetX:t.x,targetY:t.y+80,lifeSeconds:.16}};}return {skipped:true};}});
 }
 if(id==='tidehunter_ravage'){
  const features=['legacy-field-v1','legacy-hit-v1'];num(m.wave_speed_wu_s,'wave_speed_wu_s',Number.MIN_VALUE);num(m.radius_wu/m.wave_speed_wu_s+.1,'derived expansion life',0,3600);
  return build(features,['legacy-effect','damage'],{activate(ctx,e){gate(config,e,features);return {effectHandle:ctx.legacyEffect.spawn({owner:e.owner,abilityId:id,castId:handle(e.castId),kind:'area',x:ctx.actor(e.owner).x,radius:m.radius_wu,duration:m.radius_wu/m.wave_speed_wu_s+.1,data:{profile:'legacy-expanding-ravage',waveSpeed:m.wave_speed_wu_s,oneHit:true,heightPolicy:'ignore',hitboxPadding:0,contactHandler:'legacy-ravage-contact',sourceDeathPolicy:'retain'}}),presentation:ring(e.owner,m.radius_wu)};},onContact(ctx,e){gate(config,e,features);if(e.kind!=='legacy-ravage-contact')throw Error('Wrong Ravage contact');handle(e.handle);const distance=Math.abs(ctx.actor(e.target).x-num(e.effectX,'effectX',0,1200)),age=num(e.ageSeconds,'ageSeconds');if(distance>age*m.wave_speed_wu_s||distance>m.radius_wu)return {skipped:true};ctx.damage(hit(definition,e.owner,e.target));return {effectMarkHit:{handle:e.handle}};}});
 }
 return null;
}
